In [338]:
# Import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
import datetime
import xml.etree.ElementTree as ET

pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [339]:
# Import World Bank Tourism Arrival CSV file

df_arrivals_original = pd.read_csv('API_ST.INT.ARVL_DS2_en_csv_v2_1740745.csv', header=2)
df_arrivals = df_arrivals_original.copy()

df_arrivals.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Aruba,ABW,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,619000.0,641000.0,650000.0,647000.0,683000.0,721000.0,691000.0,643000.0,642000.0,728000.0,733000.0,694000.0,772000.0,827000.0,813000.0,824000.0,869000.0,904000.0,979000.0,1072000.0,1225000.0,1102000.0,1070500.0,1082000.0,NaN,NaN,NaN
1,Afghanistan,AFG,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9000.0,21000.0,45000.0,52000.0,45000.0,51000.0,67000.0,91000.0,107000.0,194000.0,210000.0,121000.0,195000.0,294000.0,366000.0,425000.0,481000.0,528000.0,650000.0,595000.0,592000.0,397000.0,261000.0,218000.0,NaN,NaN,NaN
3,Albania,ALB,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1062000.0,1247000.0,1711000.0,2191000.0,2469000.0,3156000.0,2857000.0,3341000.0,3784000.0,4070000.0,4643000.0,5340000.0,NaN,NaN,NaN
4,Andorra,AND,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2347000.0,2949000.0,3516000.0,3387000.0,3138000.0,2791000.0,2418000.0,2227000.0,2189000.0,2059000.0,1830000.0,1808000.0,2242000.0,2238000.0,2328000.0,2363000.0,2663000.0,2819000.0,3003000.0,3042000.0,NaN,NaN,NaN

In [340]:
# Filter Tourism Arrival to keep needed columns (years)

cols_keep = ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code']
years_keep = []
for year in range(2012, 2019):
    years_keep.append(str(year))
cols_keep = cols_keep + years_keep
df_arrivals = df_arrivals[cols_keep]

# Drop countries (rows) with any missing values in relevant years

df_arrivals = df_arrivals.dropna()

# Convert from wide to long format

df_arrivals = pd.melt(df_arrivals, id_vars =['Country Name', 'Country Code'], value_vars = years_keep) 

#print(df_arrivals.dtypes)
df_arrivals.head()

  Country Name Country Code variable         value
0        Aruba          ABW     2012  9.040000e+05
1       Angola          AGO     2012  5.280000e+05
2      Albania          ALB     2012  3.156000e+06
3      Andorra          AND     2012  2.238000e+06
4   Arab World          ARB     2012  8.484459e+07

In [341]:
#### USE THIS CELL TO IMPORT FROM AN XML ONCE ERROR IS RESOLVED ####

# Import World Bank Population XML file

#------------

# XML parsing code adapted from:
# https://stackabuse.com/reading-and-writing-xml-files-in-python-with-pandas/

# xml_data = open('API_SP.POP.TOTL_DS2_en_xml_v2_1741834.xml', 'r').read()  # Read file
# root = ET.XML(xml_data)  # Parse XML
# data = []
# xml_cols = []
# for i, child in enumerate(root):
#     data.append([subchild.text for subchild in child])
#     xml_cols.append(child.tag)

# df_population_original = pd.DataFrame(data).T  # Write in DF and transpose it
# df_population_original.columns = xml_cols  # Update column names
# df_population = df_population_original.copy()

# df_population.head()

#------------

# from lxml import objectify
# import pandas as pd

# xml_data = objectify.parse('test1.xml')  # Parse XML data
# root = xml_data.getroot()  # Root element

# data = []
# cols = []
# for i in range(len(root.getchildren())):
#     child = root.getchildren()[i]
#     data.append([subchild.text for subchild in child.getchildren()])
#     cols.append(child.tag)

# df = pd.DataFrame(data).T  # Create DataFrame and transpose it
# df.columns = cols  # Update column names
# print(df)

#-----------

# # import required modules 
# from bs4 import BeautifulSoup 
  
# # reading content 
# file = open("test1.xml", "r") 
# contents = file.read() 
  
# # parsing 
# soup = BeautifulSoup(contents, 'xml') 
# titles = soup.find_all('title') 
  
# # display content 
# for data in titles: 
#     print(data.get_text()) 

#-------------

# API_ST.INT.ARVL_DS2_en_csv_v2_1740745.csv
# API_SP.POP.TOTL_DS2_en_xml_v2_1741834.xml

#  df_population.head(300)

In [342]:
# Import World Bank Population CSV file

df_population_original = pd.read_csv('API_SP.POP.TOTL_DS2_en_csv_v2_1835328.csv', header=2)
df_population = df_population_original.copy()

df_population.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54211.0,55438.0,56225.0,56695.0,57032.0,57360.0,57715.0,58055.0,58386.0,58726.0,59063.0,59440.0,59840.0,60243.0,60528.0,60657.0,60586.0,60366.0,60103.0,59980.0,60096.0,60567.0,61345.0,62201.0,62836.0,63026.0,62644.0,61833.0,61079.0,61032.0,62149.0,64622.0,68235.0,72504.0,76700.0,80324.0,83200.0,85451.0,87277.0,89005.0,90853.0,92898.0,94992.0,97017.0,98737.0,100031.0,100834.0,101222.0,101358.0,101455.0,101669.0,102046.0,102560.0,103159.0,103774.0,104341.0,104872.0,105366.0,105845.0,106314.0,NaN,NaN
1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996973.0,9169410.0,9351441.0,9543205.0,9744781.0,9956320.0,10174836.0,10399926.0,10637063.0,10893776.0,11173642.0,11475445.0,11791215.0,12108963.0,12412950.0,12689160.0,12943093.0,13171306.0,13341198.0,13411056.0,13356511.0,13171673.0,12882528.0,12537730.0,12204292.0,11938208.0,11736179.0,11604534.0,11618005.0,11868877.0,12412308.0,13299017.0,14485546.0,15816603.0,17075727.0,18110657.0,18853437.0,19357126.0,19737765.0,20170844.0,20779953.0,21606988.0,22600770.0,23680871.0,24726684.0,25654277.0,26433049.0,27100536.0,27722276.0,28394813.0,29185507.0,30117413.0,31161376.0,32269589.0,33370794.0,34413603.0,35383128.0,36296400.0,37172386.0,38041754.0,NaN,NaN
2,Angola,AGO,"Population, total",SP.POP.TOTL,5454933.0,5531472.0,5608539.0,5679458.0,5735044.0,5770570.0,5781214.0,5774243.0,5771652.0,5803254.0,5890365.0,6040777.0,6248552.0,6496962.0,6761380.0,7024000.0,7279509.0,7533735.0,7790707.0,8058067.0,8341289.0,8640446.0,8952950.0,9278096.0,9614754.0,9961997.0,10320111.0,10689250.0,11068050.0,11454777.0,11848386.0,12248901.0,12657366.0,13075049.0,13503747.0,13945206.0,14400719.0,14871570.0,15359601.0,15866869.0,16395473.0,16945753.0,17519417.0,18121479.0,18758145.0,19433602.0,20149901.0,20905363.0,21695634.0,22514281.0,23356246.0,24220661.0,25107931.0,26015780.0,26941779.0,27884381.0,28842484.0,29816748.0,30809762.0,31825295.0,NaN,NaN
3,Albania,ALB,"Population, total",SP.POP.TOTL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,1914573.0,1965598.0,2022272.0,2081695.0,2135479.0,2187853.0,2243126.0,2296752.0,2350124.0,2404831.0,2458526.0,2513546.0,2566266.0,2617832.0,2671997.0,2726056.0,2784278.0,2843960.0,2904429.0,2964762.0,3022635.0,3083605.0,3142336.0,3227943.0,3286542.0,3266790.0,3247039.0,3227287.0,3207536.0,3187784.0,3168033.0,3148281.0,3128530.0,3108778.0,3089027.0,3060173.0,3051010.0,3039616.0,3026939.0,3011487.0,2992547.0,2970017.0,2947314.0,2927519.0,2913021.0,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,2866376.0,2854191.0,NaN,NaN
4,Andorra,AND,"Population, total",SP.POP.TOTL,13411.0,14375.0,15370.0,16412.0,17469.0,18549.0,19647.0,20758.0,21890.0,23058.0,24276.0,25559.0,26892.0,28232.0,29520.0,30705.0,31777.0,32771.0,33737.0,34818.0,36067.0,37500.0,39114.0,40867.0,42706.0,44600.0,46517.0,48455.0,50434.0,52448.0,54509.0,56671.0,58888.0,60971.0,62677.0,63850.0,64360.0,64327.0,64142.0,64370.0,65390.0,67341.0,70049.0,73182.0,76244.0,78867.0,80993.0,82684.0,83862.0,84463.0,84449.0,83747.0,82427.0,80774.0,79213.0,78011.0,77297.0,77001.0,77006.0,77142.0,NaN,NaN

In [343]:
# Filter Population to keep needed columns (years)

cols_keep = ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code']
years_keep = []
for year in range(2012, 2019):
    years_keep.append(str(year))
cols_keep = cols_keep + years_keep
df_population = df_population[cols_keep]

# Drop countries (rows) with any missing values in relevant years

df_population = df_population.dropna()

# Convert from wide to long format

df_population = pd.melt(df_population, id_vars =['Country Name', 'Country Code'], value_vars = years_keep) 

# df_population.dtypes
df_population.head()

  Country Name Country Code variable       value
0        Aruba          ABW     2012    102560.0
1  Afghanistan          AFG     2012  31161376.0
2       Angola          AGO     2012  25107931.0
3      Albania          ALB     2012   2900401.0
4      Andorra          AND     2012     82427.0

In [344]:
# Join Tourism Arrival and Population dfs

tourism_pop_df = df_arrivals.merge(df_population, left_on=['Country Code', 'variable'], 
                                   right_on = ['Country Code', 'variable'], how='left')

# Clean up columns and column names

tourism_pop_df = tourism_pop_df.rename(columns={"Country Name_x": "country_txt_wb", "Country Code": "country_code", "variable": "year_wb", "value_x": "arrivals", "value_y": "population"})
tourism_pop_df = tourism_pop_df[["country_txt_wb", "country_code", "year_wb", "arrivals", "population"]]

tourism_pop_df.head()

  country_txt_wb country_code year_wb      arrivals   population
0          Aruba          ABW    2012  9.040000e+05     102560.0
1         Angola          AGO    2012  5.280000e+05   25107931.0
2        Albania          ALB    2012  3.156000e+06    2900401.0
3        Andorra          AND    2012  2.238000e+06      82427.0
4     Arab World          ARB    2012  8.484459e+07  371443547.0

In [345]:
# Import mapping CSV file between GTD country IDs and WB country codes (CSV file)

df_country_mapping_original = pd.read_csv('gtd_to_wb_country_mapping.csv', header=0)
df_country_mapping = df_country_mapping_original.copy()
df_country_mapping = df_country_mapping.drop(df_country_mapping.index[0])

df_country_mapping.head()

   country_id      gtd_name wb_country_code      wb_name
1         4.0   Afghanistan             AFG  Afghanistan
2         5.0       Albania             ALB      Albania
3         6.0       Algeria             DZA      Algeria
4         7.0       Andorra             AND      Andorra
5         8.0        Angola             AGO       Angola

In [346]:
# Join GTD country IDs to final tourism + Population dataframe

tourism_pop_df = tourism_pop_df.merge(df_country_mapping, left_on=['country_code'], 
                                   right_on = ['wb_country_code'], how='left')
tourism_pop_df = tourism_pop_df.drop(['gtd_name', 'wb_country_code', 'wb_name'], axis=1)

# Clean up by reordering columns and casting appropriate columns as integers

tourism_pop_df = tourism_pop_df[['year_wb', 'country_id', 'country_txt_wb', 'country_code', 'arrivals', 'population']]

# Drop countries (rows) where there is not a country_id (from GTD) for the WB country code

tourism_pop_df = tourism_pop_df.dropna()
tourism_pop_df = tourism_pop_df.reset_index(drop=True)

# Cast relevant columns to integers

tourism_pop_df['year_wb'] = tourism_pop_df['year_wb'].astype(int) 
tourism_pop_df['country_id'] = tourism_pop_df['country_id'].astype(int) 
tourism_pop_df['arrivals'] = tourism_pop_df['arrivals'].astype(int) 
tourism_pop_df['population'] = tourism_pop_df['population'].astype(int) 

#print(tourism_pop_df.dtypes)
tourism_pop_df.head(5000)

,year_wb,country_id,country_txt_wb,country_code,arrivals,population
0,2012,8,Angola,AGO,528000,25107931
1,2012,5,Albania,ALB,3156000,2900401
2,2012,7,Andorra,AND,2238000,82427
3,2012,11,Argentina,ARG,6497000,41733271
4,2012,12,Armenia,ARM,963000,2884229
5,2012,10,Antigua and Barbuda,ATG,247000,90409
6,2012,14,Australia,AUS,6032000,22733465
7,2012,15,Austria,AUT,24151000,8429991
8,2012,16,Azerbaijan,AZE,1986000,9295784
9,2012,21,Belgium,BEL,7560000,11106932
10,2012,23,Benin,BEN,220000,9729248
11,2012,33,Burkina Faso,BFA,237000,16571246
12,2012,32,Bulgaria,BGR,6541000,7305888
13,2012,18,Bahrain,BHR,8062000,1299943
14,2012,17,"Bahamas, The",BHS,1422000,363584
15,2012,28,Bosnia and Herzegovina,BIH,439000,3604972
16,2012,35,Belarus,BLR,6129900,9464495
17,2012,22,Belize,BLZ,277000,338000
18,2012,24,Bermuda,BMU,232000,64798
19,2012,26,Bolivia,BOL,798000,10377676
20,2012,30,Brazil,BRA,5677000,199287296
21,2012,20,Barbados,BRB,536000,283700
22,2012,31,Brunei Darussalam,BRN,209000,398989
23,2012,25,Bhutan,BTN,105000,701583
24,2012,38,Canada,CAN,16344000,34714222
25,2012,199,Switzerland,CHE,8566000,7996861
26,2012,43,Chile,CHL,3554000,17400347
27,2012,44,China,CHN,57725000,1350695000
28,2012,99,Cote d'Ivoire,CIV,289000,21547188
29,2012,47,"Congo, Rep.",COG,256000,4510198
30,2012,45,Colombia,COL,2179000,46076848
31,2012,46,Comoros,COM,22800,723871
32,2012,49,Costa Rica,CRI,2343000,4688000
33,2012,51,Cuba,CUB,2823000,11257101
34,2012,53,Cyprus,CYP,2465000,1135046
35,2012,54,Czech Republic,CZE,7647000,10510785
36,2012,75,Germany,DEU,30411000,80425823
37,2012,57,Dominica,DMA,79000,70965
38,2012,55,Denmark,DNK,8443000,5591572
39,2012,58,Dominican Republic,DOM,4563000,9930911
40,2012,6,Algeria,DZA,2634000,37383887
41,2012,59,Ecuador,ECU,1272000,15474102
42,2012,60,"Egypt, Arab Rep.",EGY,11196000,86422240
43,2012,185,Spain,ESP,57464000,46773055
44,2012,64,Estonia,EST,2957000,1322696
45,2012,65,Ethiopia,ETH,597000,92726971
46,2012,68,Finland,FIN,2778000,5413971
47,2012,67,Fiji,FJI,661000,865069
48,2012,69,France,FRA,81980000,65659809
49,2012,603,United Kingdom,GBR,29282000,63700215
50,2012,74,Georgia,GEO,2460000,3728874
51,2012,73,"Gambia, The",GMB,157000,1905011
52,2012,78,Greece,GRC,15518000,11045011
53,2012,80,Grenada,GRD,125000,107446
54,2012,83,Guatemala,GTM,1200000,14781942
55,2012,86,Guyana,GUY,177000,755399
56,2012,89,"Hong Kong SAR, China",HKG,23770000,7150100
57,2012,50,Croatia,HRV,10369000,4267558
58,2012,87,Haiti,HTI,349000,10250930
59,2012,90,Hungary,HUN,10353000,9920362
60,2012,93,Indonesia,IDN,8044000,248452413
61,2012,92,India,IND,6578000,1265782790
62,2012,96,Ireland,IRL,7550000,4599533
63,2012,94,"Iran, Islamic Rep.",IRN,3834000,75539862
64,2012,91,Iceland,ISL,673000,320716
65,2012,97,Israel,ISR,2886000,7910500
66,2012,98,Italy,ITA,46360000,59539717
67,2012,100,Jamaica,JAM,1986000,2842132
68,2012,102,Jordan,JOR,4162000,8090872
69,2012,101,Japan,JPN,8358000,127629000
70,2012,103,Kazakhstan,KAZ,6163000,16792089
71,2012,107,Kyrgyz Republic,KGZ,348000,5607200
72,2012,36,Cambodia,KHM,3584000,14780454
73,2012,189,St. Kitts and Nevis,KNA,104000,49887
74,2012,184,"Korea, Rep.",KOR,11140000,50199853
75,2012,106,Kuwait,KWT,5729000,3348853
76,2012,108,Lao PDR,LAO,2291000,6444530
77,2012,110,Lebanon,LBN,1366000,5538634
78,2012,190,St. Lucia,LCA,307000,176646
79,2012,114,Liechtenstein,LIE,62400,36615
80,2012,186,Sri Lanka,LKA,1006000,20425000
81,2012,111,Lesotho,LSO,423000,2014990
82,2012,115,Lithuania,LTU,1900000,2987773
83,2012,116,Luxembourg,LUX,950000,530946
84,2012,109,Latvia,LVA,1435000,2034319
85,2012,117,"Macao SAR, China",MAC,13577000,564039
86,2012,136,Morocco,MAR,9375000,33241898
87,2012,132,Moldova,MDA,89000,2859458
88,2012,119,Madagascar,MDG,256000,22346641
89,2012,122,Maldives,MDV,958000,397237
90,2012,130,Mexico,MEX,23403000,117274155
91,2012,118,North Macedonia,MKD,351000,2074278
92,2012,123,Mali,MLI,32000,15979499
93,2012,124,Malta,MLT,1443000,420028
94,2012,138,Myanmar,MMR,1059000,51413698
95,2012,1002,Montenegro,MNE,1264000,620601
96,2012,134,Mongolia,MNG,476000,2824699
97,2012,137,Mozambique,MOZ,2113000,24862648
98,2012,129,Mauritius,MUS,965000,1255882
99,2012,120,Malawi,MWI,770000,15396005
100,2012,121,Malaysia,MYS,25033000,29068159
101,2012,143,New Caledonia,NCL,112000,259000
102,2012,146,Niger,NER,94000,17795191
103,2012,145,Nicaragua,NIC,1180000,5982526
104,2012,142,Netherlands,NLD,11680000,16754962
105,2012,151,Norway,NOR,4538000,5018573
106,2012,141,Nepal,NPL,803000,26989862
107,2012,144,New Zealand,NZL,2473000,4408100
108,2012,152,Oman,OMN,1241000,3498029
109,2012,156,Panama,PAN,1606000,3770624
110,2012,159,Peru,PER,2846000,29506788
111,2012,160,Philippines,PHL,4273000,97212638
112,2012,157,Papua New Guinea,PNG,168000,7631002
113,2012,161,Poland,POL,14840000,38063164
114,2012,163,Puerto Rico,PRI,3069000,3634488
115,2012,162,Portugal,PRT,7503000,10514844
116,2012,158,Paraguay,PRY,579000,6421512
117,2012,155,West Bank and Gaza,PSE,490000,3979998
118,2012,71,French Polynesia,PYF,169000,268998
119,2012,164,Qatar,QAT,2323500,2196074
120,2012,166,Romania,ROU,7937000,20058035
121,2012,167,Russian Federation,RUS,28177000,143201721
122,2012,173,Saudi Arabia,SAU,16332000,29155187
123,2012,195,Sudan,SDN,575000,36193783
124,2012,178,Singapore,SGP,11098000,5312437
125,2012,181,Solomon Islands,SLB,23900,556064
126,2012,177,Sierra Leone,SLE,60000,6712581
127,2012,61,El Salvador,SLV,1255000,6237923
128,2012,1001,Serbia,SRB,810000,7199077
129,2012,179,Slovak Republic,SVK,1528000,5407579
130,2012,180,Slovenia,SVN,2377000,2057159
131,2012,198,Sweden,SWE,5146000,9519374
132,2012,197,Eswatini,SWZ,888000,1079288
133,2012,176,Seychelles,SYC,208000,88303
134,2012,204,Togo,TGO,235000,6773807
135,2012,205,Thailand,THA,22354000,67835957
136,2012,202,Tajikistan,TJK,244000,7874835
137,2012,347,Timor-Leste,TLS,58000,1132994
138,2012,206,Tonga,TON,47400,102737
139,2012,207,Trinidad and Tobago,TTO,455000,1344817
140,2012,208,Tunisia,TUN,6999000,10847002
141,2012,209,Turkey,TUR,35698000,74653016
142,2012,212,Tuvalu,TUV,1100,10739
143,2012,203,Tanzania,TZA,1043000,47052481
144,2012,214,Ukraine,UKR,23013000,45593342
145,2012,218,Uruguay,URY,2695000,3378974
146,2012,217,United States,USA,66966900,313830990
147,2012,219,Uzbekistan,UZB,1895000,29774500
148,2012,225,Virgin Islands (U.S.),VIR,619000,108191
149,2012,223,Vietnam,VNM,6848000,89802487
150,2012,220,Vanuatu,VUT,108200,249499
151,2012,183,South Africa,ZAF,9188000,52834005
152,2012,230,Zambia,ZMB,859000,14465121
153,2012,231,Zimbabwe,ZWE,1794000,13115131
154,2013,8,Angola,AGO,650000,26015780
155,2013,5,Albania,ALB,2857000,2895092
156,2013,7,Andorra,AND,2328000,80774
157,2013,11,Argentina,ARG,6510000,42202935
158,2013,12,Armenia,ARM,1084000,2897584
159,2013,10,Antigua and Barbuda,ATG,243000,91516
160,2013,14,Australia,AUS,6482000,23128129
161,2013,15,Austria,AUT,24813000,8479823
162,2013,16,Azerbaijan,AZE,2130000,9416801
163,2013,21,Belgium,BEL,7684000,11159407
164,2013,23,Benin,BEN,231000,10004588
165,2013,33,Burkina Faso,BFA,218000,17072775
166,2013,32,Bulgaria,BGR,6898000,7265115
167,2013,18,Bahrain,BHR,9163000,1315029
168,2013,17,"Bahamas, The",BHS,1366000,367168
169,2013,28,Bosnia and Herzegovina,BIH,529000,3542605
170,2013,35,Belarus,BLR,6241800,9465997
171,2013,22,Belize,BLZ,294000,345715
172,2013,24,Bermuda,BMU,236000,65001
173,2013,26,Bolivia,BOL,798000,10542376
174,2013,30,Brazil,BRA,5813000,201035903
175,2013,20,Barbados,BRB,509000,284296
176,2013,31,Brunei Darussalam,BRN,225000,404421
177,2013,25,Bhutan,BTN,116000,710238
178,2013,38,Canada,CAN,16059000,35082954
179,2013,199,Switzerland,CHE,8967000,8089346
180,2013,43,Chile,CHL,3576000,17571507
181,2013,44,China,CHN,55686000,1357380000
182,2013,99,Cote d'Ivoire,CIV,380000,22087505
183,2013,47,"Congo, Rep.",COG,343000,4622761
184,2013,45,Colombia,COL,2288000,46497267
185,2013,46,Comoros,COM,21900,741505
186,2013,49,Costa Rica,CRI,2428000,4742107
187,2013,51,Cuba,CUB,2839000,11282720
188,2013,53,Cyprus,CYP,2405000,1143866
189,2013,54,Czech Republic,CZE,7852000,10514272
190,2013,75,Germany,DEU,31545000,80645605
191,2013,57,Dominica,DMA,78000,71016
192,2013,55,Denmark,DNK,8557000,5614932
193,2013,58,Dominican Republic,DOM,4690000,10048224
194,2013,6,Algeria,DZA,2733000,38140132
195,2013,59,Ecuador,ECU,1364000,15707474
196,2013,60,"Egypt, Arab Rep.",EGY,9174000,88404640
197,2013,185,Spain,ESP,60675000,46620045
198,2013,64,Estonia,EST,3111000,1317997
199,2013,65,Ethiopia,ETH,681000,95385785
200,2013,68,Finland,FIN,2797000,5438972
201,2013,67,Fiji,FJI,659000,865608
202,2013,69,France,FRA,83634000,65998687
203,2013,603,United Kingdom,GBR,31063000,64128273
204,2013,74,Georgia,GEO,2884000,3717668
205,2013,73,"Gambia, The",GMB,171000,1963711
206,2013,78,Greece,GRC,17920000,10965211
207,2013,80,Grenada,GRD,128000,108170
208,2013,83,Guatemala,GTM,1224000,15043981
209,2013,86,Guyana,GUY,200000,759285
210,2013,89,"Hong Kong SAR, China",HKG,25661000,7178900
211,2013,50,Croatia,HRV,10948000,4255689
212,2013,87,Haiti,HTI,420000,10400673
213,2013,90,Hungary,HUN,10624000,9893082
214,2013,93,Indonesia,IDN,8802000,251806402
215,2013,92,India,IND,6968000,1280846129
216,2013,96,Ireland,IRL,8260000,4623816
217,2013,94,"Iran, Islamic Rep.",IRN,4769000,76481943
218,2013,91,Iceland,ISL,807300,323764
219,2013,97,Israel,ISR,2962000,8059500
220,2013,98,Italy,ITA,47704000,60233948
221,2013,100,Jamaica,JAM,2008400,2858709
222,2013,102,Jordan,JOR,3945000,8520420
223,2013,101,Japan,JPN,10364000,127445000
224,2013,103,Kazakhstan,KAZ,6841000,17035550
225,2013,107,Kyrgyz Republic,KGZ,415000,5719600
226,2013,36,Cambodia,KHM,4210000,15026332
227,2013,189,St. Kitts and Nevis,KNA,107000,50331
228,2013,184,"Korea, Rep.",KOR,12176000,50428893
229,2013,106,Kuwait,KWT,6217000,3526376
230,2013,108,Lao PDR,LAO,2700000,6541304
231,2013,110,Lebanon,LBN,1274000,5914621
232,2013,190,St. Lucia,LCA,319000,177513
233,2013,114,Liechtenstein,LIE,59600,36934
234,2013,186,Sri Lanka,LKA,1275000,20585000
235,2013,111,Lesotho,LSO,433000,2028519
236,2013,115,Lithuania,LTU,2012000,2957689
237,2013,116,Luxembourg,LUX,945000,543360
238,2013,109,Latvia,LVA,1536000,2012647
239,2013,117,"Macao SAR, China",MAC,14268000,577372
240,2013,136,Morocco,MAR,10046000,33715693
241,2013,132,Moldova,MDA,95600,2858692
242,2013,119,Madagascar,MDG,196000,22961253
243,2013,122,Maldives,MDV,1125000,415593
244,2013,130,Mexico,MEX,24151000,118827161
245,2013,118,North Macedonia,MKD,400000,2076067
246,2013,123,Mali,MLI,57000,16449864
247,2013,124,Malta,MLT,1582000,425967
248,2013,138,Myanmar,MMR,2044000,51852451
249,2013,1002,Montenegro,MNE,1324000,621207
250,2013,134,Mongolia,MNG,418000,2881792
251,2013,137,Mozambique,MOZ,1886000,25560725
252,2013,129,Mauritius,MUS,993000,1258653
253,2013,120,Malawi,MWI,795000,15839269
254,2013,121,Malaysia,MYS,25715000,29468872
255,2013,143,New Caledonia,NCL,108000,263650
256,2013,146,Niger,NER,123000,18504255
257,2013,145,Nicaragua,NIC,1229000,6062454
258,2013,142,Netherlands,NLD,12783000,16804432
259,2013,151,Norway,NOR,4778000,5079623
260,2013,141,Nepal,NPL,798000,26917906
261,2013,144,New Zealand,NZL,2629000,4442100
262,2013,152,Oman,OMN,1392000,3764805
263,2013,156,Panama,PAN,1658000,3835437
264,2013,159,Peru,PER,3164000,29773987
265,2013,160,Philippines,PHL,4681000,98871552
266,2013,157,Papua New Guinea,PNG,174000,7788379
267,2013,161,Poland,POL,15800000,38040196
268,2013,163,Puerto Rico,PRI,3172000,3593077
269,2013,162,Portugal,PRT,9177000,10457295
270,2013,158,Paraguay,PRY,610000,6510276
271,2013,155,West Bank and Gaza,PSE,545000,4076708
272,2013,71,French Polynesia,PYF,164000,270328
273,2013,164,Qatar,QAT,2611900,2336574
274,2013,166,Romania,ROU,8019000,19983693
275,2013,167,Russian Federation,RUS,30792000,143506995
276,2013,173,Saudi Arabia,SAU,15772000,30052518
277,2013,195,Sudan,SDN,591000,37072550
278,2013,178,Singapore,SGP,11899000,5399162
279,2013,181,Solomon Islands,SLB,24400,571335
280,2013,177,Sierra Leone,SLE,81000,6863980
281,2013,61,El Salvador,SLV,1283000,6266070
282,2013,1001,Serbia,SRB,922000,7164132
283,2013,179,Slovak Republic,SVK,1670000,5413393
284,2013,180,Slovenia,SVN,2502000,2059953
285,2013,198,Sweden,SWE,5229000,9600379
286,2013,197,Eswatini,SWZ,968000,1086839
287,2013,176,Seychelles,SYC,230000,89949
288,2013,204,Togo,TGO,327000,6954721
289,2013,205,Thailand,THA,26547000,68144501
290,2013,202,Tajikistan,TJK,208000,8059769
291,2013,347,Timor-Leste,TLS,79000,1153295
292,2013,206,Tonga,TON,48200,101768
293,2013,207,Trinidad and Tobago,TTO,434000,1353700
294,2013,208,Tunisia,TUN,7352000,10952951
295,2013,209,Turkey,TUR,37795000,75928564
296,2013,212,Tuvalu,TUV,1300,10857
297,2013,203,Tanzania,TZA,1063000,48482266
298,2013,214,Ukraine,UKR,24671000,45489648
299,2013,218,Uruguay,URY,2683000,3389439
300,2013,217,United States,USA,71642910,315993715
301,2013,219,Uzbekistan,UZB,1969000,30243200
302,2013,225,Virgin Islands (U.S.),VIR,590000,108044
303,2013,223,Vietnam,VNM,7572000,90753472
304,2013,220,Vanuatu,VUT,110000,256635
305,2013,183,South Africa,ZAF,9537000,53689236
306,2013,230,Zambia,ZMB,915000,14926504
307,2013,231,Zimbabwe,ZWE,1833000,13350356
308,2014,8,Angola,AGO,595000,26941779
309,2014,5,Albania,ALB,3341000,2889104
310,2014,7,Andorra,AND,2363000,79213
311,2014,11,Argentina,ARG,7165000,42669500
312,2014,12,Armenia,ARM,1204000,2912403
313,2014,10,Antigua and Barbuda,ATG,249000,92562
314,2014,14,Australia,AUS,6922000,23475686
315,2014,15,Austria,AUT,25291000,8546356
316,2014,16,Azerbaijan,AZE,2160000,9535079
317,2014,21,Belgium,BEL,7887000,11209057
318,2014,23,Benin,BEN,242000,10286842
319,2014,33,Burkina Faso,BFA,191000,17586017
320,2014,32,Bulgaria,BGR,7311000,7223938
321,2014,18,Bahrain,BHR,10452000,1336075
322,2014,17,"Bahamas, The",BHS,1446000,370633
323,2014,28,Bosnia and Herzegovina,BIH,536000,3482104
324,2014,35,Belarus,BLR,5374900,9474511
325,2014,22,Belize,BLZ,321000,353366
326,2014,24,Bermuda,BMU,224000,65138
327,2014,26,Bolivia,BOL,871000,10706517
328,2014,30,Brazil,BRA,6430000,202763735
329,2014,20,Barbados,BRB,521000,284825
330,2014,31,Brunei Darussalam,BRN,201000,409769
331,2014,25,Bhutan,BTN,133000,719056
332,2014,38,Canada,CAN,16537000,35437435
333,2014,199,Switzerland,CHE,9158000,8188649
334,2014,43,Chile,CHL,3674000,17758959
335,2014,44,China,CHN,55622000,1364270000
336,2014,99,Cote d'Ivoire,CIV,471000,22647683
337,2014,47,"Congo, Rep.",COG,226000,4736974
338,2014,45,Colombia,COL,2552000,46969209
339,2014,46,Comoros,COM,22800,759390
340,2014,49,Costa Rica,CRI,2527000,4795396
341,2014,51,Cuba,CUB,2981000,11306902
342,2014,53,Cyprus,CYP,2441000,1152285
343,2014,54,Czech Republic,CZE,8096000,10525347
344,2014,75,Germany,DEU,32999000,80982500
345,2014,57,Dominica,DMA,81500,71085
346,2014,55,Denmark,DNK,10267000,5643475
347,2014,58,Dominican Republic,DOM,5141400,10165178
348,2014,6,Algeria,DZA,2301000,38923687
349,2014,59,Ecuador,ECU,1695000,15951838
350,2014,60,"Egypt, Arab Rep.",EGY,9628300,90424654
351,2014,185,Spain,ESP,64939000,46480882
352,2014,64,Estonia,EST,3160000,1314545
353,2014,65,Ethiopia,ETH,770000,98094253
354,2014,68,Finland,FIN,2731000,5461512
355,2014,67,Fiji,FJI,693000,866453
356,2014,69,France,FRA,83701000,66312067
357,2014,603,United Kingdom,GBR,32613000,64602298
358,2014,74,Georgia,GEO,2939000,3719414
359,2014,73,"Gambia, The",GMB,156000,2024042
360,2014,78,Greece,GRC,22033000,10892413
361,2014,80,Grenada,GRD,150000,108902
362,2014,83,Guatemala,GTM,1371000,15306316
363,2014,86,Guyana,GUY,206000,763380
364,2014,89,"Hong Kong SAR, China",HKG,27770000,7229500
365,2014,50,Croatia,HRV,11623000,4238389
366,2014,87,Haiti,HTI,465200,10549008
367,2014,90,Hungary,HUN,12140000,9866468
368,2014,93,Indonesia,IDN,9435000,255129004
369,2014,92,India,IND,13107000,1295604184
370,2014,96,Ireland,IRL,8813000,4657740
371,2014,94,"Iran, Islamic Rep.",IRN,4968000,77465753
372,2014,91,Iceland,ISL,997000,327386
373,2014,97,Israel,ISR,2927000,8215700
374,2014,98,Italy,ITA,48576000,60789140
375,2014,100,Jamaica,JAM,2080000,2875136
376,2014,102,Jordan,JOR,3990000,8920049
377,2014,101,Japan,JPN,13413000,127276000
378,2014,103,Kazakhstan,KAZ,6333000,17288285
379,2014,107,Kyrgyz Republic,KGZ,413000,5835500
380,2014,36,Cambodia,KHM,4503000,15274503
381,2014,189,St. Kitts and Nevis,KNA,113000,50774
382,2014,184,"Korea, Rep.",KOR,14202000,50746659
383,2014,106,Kuwait,KWT,6528000,3690941
384,2014,108,Lao PDR,LAO,3164000,6639756
385,2014,110,Lebanon,LBN,1355000,6262410
386,2014,190,St. Lucia,LCA,338000,178296
387,2014,114,Liechtenstein,LIE,61300,37223
388,2014,186,Sri Lanka,LKA,1527000,20778000
389,2014,111,Lesotho,LSO,1079000,2043437
390,2014,115,Lithuania,LTU,2063000,2932367
391,2014,116,Luxembourg,LUX,1038000,556319
392,2014,109,Latvia,LVA,1843000,1993782
393,2014,117,"Macao SAR, China",MAC,14566000,590208
394,2014,136,Morocco,MAR,10283000,34192347
395,2014,132,Moldova,MDA,93900,2856950
396,2014,119,Madagascar,MDG,222000,23589887
397,2014,122,Maldives,MDV,1205000,435015
398,2014,130,Mexico,MEX,29346000,120355128
399,2014,118,North Macedonia,MKD,425000,2077775
400,2014,123,Mali,MLI,53000,16934220
401,2014,124,Malta,MLT,1690000,434558
402,2014,138,Myanmar,MMR,3081000,52280807
403,2014,1002,Montenegro,MNE,1350000,621810
404,2014,134,Mongolia,MNG,393000,2940108
405,2014,137,Mozambique,MOZ,1661000,26286163
406,2014,129,Mauritius,MUS,1038000,1260934
407,2014,120,Malawi,MWI,819000,16289540
408,2014,121,Malaysia,MYS,27437000,29866559
409,2014,143,New Caledonia,NCL,107000,268050
410,2014,146,Niger,NER,135000,19240157
411,2014,145,Nicaragua,NIC,1330000,6142733
412,2014,142,Netherlands,NLD,13925000,16865008
413,2014,151,Norway,NOR,4855000,5137232
414,2014,141,Nepal,NPL,790000,26906926
415,2014,144,New Zealand,NZL,2772000,4509700
416,2014,152,Oman,OMN,1611000,4027260
417,2014,156,Panama,PAN,1745000,3901315
418,2014,159,Peru,PER,3215000,30090359
419,2014,160,Philippines,PHL,4833000,100513138
420,2014,157,Papua New Guinea,PNG,182000,7946731
421,2014,161,Poland,POL,16000000,38011735
422,2014,163,Puerto Rico,PRI,3246000,3534874
423,2014,162,Portugal,PRT,10497000,10401062
424,2014,158,Paraguay,PRY,649000,6599526
425,2014,155,West Bank and Gaza,PSE,556000,4173398
426,2014,71,French Polynesia,PYF,181000,271705
427,2014,164,Qatar,QAT,2839200,2459198
428,2014,166,Romania,ROU,8442000,19908979
429,2014,167,Russian Federation,RUS,32421000,143819666
430,2014,173,Saudi Arabia,SAU,18260000,30916994
431,2014,195,Sudan,SDN,684000,37977655
432,2014,178,Singapore,SGP,11864000,5469724
433,2014,181,Solomon Islands,SLB,20100,587079
434,2014,177,Sierra Leone,SLE,44000,7017144
435,2014,61,El Salvador,SLV,1345000,6295128
436,2014,1001,Serbia,SRB,1029000,7130576
437,2014,179,Slovak Republic,SVK,1475000,5418649
438,2014,180,Slovenia,SVN,2675000,2061980
439,2014,198,Sweden,SWE,5660000,9696110
440,2014,197,Eswatini,SWZ,939000,1095021
441,2014,176,Seychelles,SYC,233000,91359
442,2014,204,Togo,TGO,282000,7137997
443,2014,205,Thailand,THA,24810000,68438730
444,2014,202,Tajikistan,TJK,213000,8252833
445,2014,347,Timor-Leste,TLS,60000,1174331
446,2014,206,Tonga,TON,50400,101028
447,2014,207,Trinidad and Tobago,TTO,412000,1362342
448,2014,208,Tunisia,TUN,7163000,11063201
449,2014,209,Turkey,TUR,39811000,77231907
450,2014,212,Tuvalu,TUV,1400,10972
451,2014,203,Tanzania,TZA,1113000,49959822
452,2014,214,Ukraine,UKR,12712000,45272156
453,2014,218,Uruguay,URY,2682000,3400434
454,2014,217,United States,USA,75379350,318301008
455,2014,219,Uzbekistan,UZB,1862000,30757700
456,2014,225,Virgin Islands (U.S.),VIR,615000,107884
457,2014,223,Vietnam,VNM,7874000,91714595
458,2014,220,Vanuatu,VUT,109000,263888
459,2014,183,South Africa,ZAF,9549000,54545991
460,2014,230,Zambia,ZMB,947000,15399753
461,2014,231,Zimbabwe,ZWE,1880000,13586681
462,2015,8,Angola,AGO,592000,27884381
463,2015,5,Albania,ALB,3784000,2880703
464,2015,7,Andorra,AND,2663000,78011
465,2015,11,Argentina,ARG,6816000,43131966
466,2015,12,Armenia,ARM,1192000,2925553
467,2015,10,Antigua and Barbuda,ATG,250000,93566
468,2015,14,Australia,AUS,7449000,23815995
469,2015,15,Austria,AUT,26728000,8642699

In [347]:
# Write final output of WB Tourism and Poluation data (with a matched GTD county_id) to a CSV file

tourism_pop_df.to_csv('tourism_pop.csv')