# Import and setup

In [1]:
import pandas as pd

In [2]:
# change display options
pd.options.display.max_rows = 150
pd.options.display.max_columns = 150

In [3]:
# import terrorism data (may take a few minutes to load)
df = pd.read_excel('../data/raw/globalterrorismdb_0919dist.xlsx')

# Explore dataset

In [4]:
# look at sample of dataset
df.sample(5)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,region_txt,provstate,city,latitude,longitude,specificity,vicinity,location,summary,crit1,crit2,crit3,doubtterr,alternative,alternative_txt,multiple,success,suicide,attacktype1,attacktype1_txt,attacktype2,attacktype2_txt,attacktype3,attacktype3_txt,targtype1,targtype1_txt,targsubtype1,targsubtype1_txt,corp1,target1,natlty1,natlty1_txt,targtype2,targtype2_txt,targsubtype2,targsubtype2_txt,corp2,target2,natlty2,natlty2_txt,targtype3,targtype3_txt,targsubtype3,targsubtype3_txt,corp3,target3,natlty3,natlty3_txt,gname,gsubname,gname2,gsubname2,gname3,gsubname3,motive,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claimmode_txt,claim2,claimmode2,claimmode2_txt,claim3,claimmode3,claimmode3_txt,compclaim,weaptype1,weaptype1_txt,weapsubtype1,weapsubtype1_txt,weaptype2,weaptype2_txt,weapsubtype2,weapsubtype2_txt,weaptype3,weaptype3_txt,weapsubtype3,weapsubtype3_txt,weaptype4,weaptype4_txt,weapsubtype4,weapsubtype4_txt,weapdetail,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propextent_txt,propvalue,propcomment,ishostkid,nhostkid,nhostkidus,nhours,ndays,divert,kidhijcountry,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,ransomnote,hostkidoutcome,hostkidoutcome_txt,nreleased,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
95374,201002140022,2010,2,14,NaN,0,NaT,95,Iraq,10,Middle East & North Africa,Baghdad,Baghdad,33.303566,44.371773,1.0,0,The attack took place in the Hayy al 'Amil nei...,"02/14/2010: On Sunday, in the southwestern Hay...",1,1,1,0,NaN,NaN,0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,14,Private Citizens & Property,67.0,Unnamed Civilian/Unspecified,NaN,The targets of this attack were civilians.,95.0,Iraq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,The specific motive for the attack is unknown.,0.0,NaN,NaN,0,-99.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,Explosives,17.0,Other Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Two improvised explosive devices were used in ...,1.0,0.0,0.0,3.0,0.0,0.0,-9,4.0,Unknown,NaN,It is unknown if the attack caused any propert...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It is unknown if civilians were the target of ...,"Reuters, ""FACTBOX-Security Developments in Ira...","National Counterterrorism Center, ""One Civilia...",NaN,ISVG,-9,-9,0,-9,NaN
50741,199203240024,1992,3,24,NaN,0,NaT,75,Germany,8,Western Europe,Berlin,Berlin,52.501530,13.401851,1.0,0,NaN,NaN,1,1,1,0,NaN,NaN,0,1,0,9,Unknown,NaN,NaN,NaN,NaN,1,Business,3.0,Bank/Commerce,Turkish Bank,Branch,209.0,Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kurdistan Workers' Party (PKK),NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,1,0,1,1,NaN
59641,199506220005,1995,6,22,NaN,0,NaT,153,Pakistan,6,South Asia,Sindh,Karachi,24.891115,67.143311,1.0,0,NaN,NaN,1,1,1,0,NaN,NaN,1,1,0,2,Armed Assault,NaN,NaN,NaN,NaN,14,Private Citizens & Property,84.0,Political Party Member/Rally,Sipah-I-Sahaba (SSP),Home of SSP activist,153.0,Pakistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Muttahida Qami Movement (MQM),NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Incendiary,0.0,NaN,NaN,0.0,NaN,NaN,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,"199506220005, 199506220006"
80032,200602260002,2006,2,26,NaN,0,NaT,4,Afghanistan,6,South Asia,Farah,Farah,32.370010,62.128456,1.0,1,NaN,02/26/2006: A remote-controlled bomb exploded ...,1,1,1,0,NaN,NaN,0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,2,Government (General),20.0,Intelligence,Intelligence operative,"Intelligence operatives in Farah province, Afg...",4.0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Taliban,NaN,NaN,NaN,NaN,NaN,Unknown,1.0,NaN,NaN,0,NaN,0.0,1.0,10.0,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,-9.0,6,Explosives,16.0,Unknown Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,2.0,NaN,0.0,1,3.0,Minor (likely < $1 million),NaN,The explosion damaged the vehicle in which the...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"“Intelligence Official Killed, Two Injured in ...",NaN,NaN,CETIS,0,0,0,0,NaN
117844,201306040007,2013,6,4,NaN,0,NaT,4,Afghanistan,6,South Asia,Helmand,Sangin district,32.073333,64.833889,3.0,0,NaN,06/04/2013: An explosive device detonated in S...,1,1,1,0,NaN,NaN,0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,14,Private Citizens & Property,67.0,Unnamed Civilian/Unspecified,Not Applicable,Civilians,4.0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Taliban,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,-99.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,Explosives,8.0,Landmine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Casualty numbers for this attack represent an ...,"""Twin explosions kill 6 civilians in southern ...","""Afghanistan: : Twin explosions kill 6 civilia...","""Xinhua: 1st LD Writethru: Roadside Bomb Kills...",START Primary Collection,0,0,0,0,NaN

In [5]:
# describe dataset
df.describe()

,eventid,iyear,imonth,iday,extended,country,region,latitude,longitude,specificity,vicinity,crit1,crit2,crit3,doubtterr,alternative,multiple,success,suicide,attacktype1,attacktype2,attacktype3,targtype1,targsubtype1,natlty1,targtype2,targsubtype2,natlty2,targtype3,targsubtype3,natlty3,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claim2,claimmode2,claim3,claimmode3,compclaim,weaptype1,weapsubtype1,weaptype2,weapsubtype2,weaptype3,weapsubtype3,weaptype4,weapsubtype4,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propvalue,ishostkid,nhostkid,nhostkidus,nhours,ndays,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,hostkidoutcome,nreleased,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
count,1.914640e+05,191464.000000,191464.000000,191464.000000,191464.000000,191464.000000,191464.000000,186884.000000,186883.000000,191463.000000,191464.000000,191464.00000,191464.000000,191464.000000,191464.000000,31070.000000,191464.000000,191464.000000,191464.000000,191464.000000,7023.000000,485.000000,191464.000000,180465.000000,189742.000000,12196.000000,11732.000000,11879.000000,1313.000000,1234.000000,1284.000000,191084.000000,2158.000000,352.000000,191464.00000,120355.000000,121981.000000,125349.000000,21550.000000,2093.000000,664.000000,350.000000,134.000000,4890.000000,191464.000000,169178.000000,14192.000000,12492.000000,2034.000000,1844.000000,73.000000,70.000000,180435.000000,127021.000000,124030.000000,173905.000000,126764.000000,121594.000000,191464.000000,67286.000000,4.219600e+04,191286.000000,14626.000000,14571.000000,4381.000000,8861.000000,78428.000000,1.416000e+03,6.230000e+02,8.380000e+02,611.000000,12045.000000,11454.000000,191464.000000,191464.000000,191464.000000,191464.000000
mean,2.003486e+11,2003.420136,6.462510,15.507688,0.047476,131.290446,7.205167,23.462121,28.902126,1.458172,0.069151,0.98841,0.993127,0.872838,-0.485757,1.297039,0.139415,0.886825,0.036618,3.276099,3.809056,5.327835,8.449259,46.976367,127.285509,10.167842,55.005114,128.984847,10.113481,55.771475,141.047508,0.079285,0.269694,0.201705,0.00351,-66.502140,-1.436117,0.065497,7.055452,0.246536,7.222892,0.377143,6.701493,-6.230061,6.472141,11.101709,6.853086,10.918268,6.971976,11.862256,6.246575,10.842857,2.410735,0.043079,0.529186,3.161232,0.037526,0.118600,-0.629319,3.291978,1.932884e+05,0.056842,4.087447,-0.334912,-49.963422,-33.179664,-0.154384,3.057619e+06,5.227734e+05,6.961705e+05,217.004910,4.643005,-29.816309,-4.521727,-4.439247,0.088951,-3.930582
std,1.334949e+09,13.349405,3.388515,8.807727,0.212656,112.058063,2.923811,18.405309,57.231040,0.991536,0.284292,0.10703,0.082621,0.333156,2.399609,0.723066,0.346380,0.316808,0.187822,1.947979,2.307806,2.234623,6.640723,30.833421,89.795208,5.709859,25.612896,124.532178,5.689909,26.114098,162.385505,0.270183,0.443904,0.401844,0.05914,208.104397,12.504317,1.058084,2.403405,0.934977,2.718301,0.485365,2.883789,4.268216,2.207859,6.494063,2.292732,7.642624,2.191003,8.575762,1.507212,8.192672,11.445411,5.461232,4.339206,42.679122,2.949192,1.544178,3.212640,0.484213,1.492315e+07,0.499810,195.153254,6.635037,80.908500,125.390956,1.240840,2.951278e+07,6.730057e+06,9.792528e+06,2796.042504,2.034429,65.183303,4.543713,4.639931,0.556741,4.689726
min,1.970000e+11,1970.000000,0.000000,0.000000,0.000000,4.000000,1.000000,-53.154613,-176.176447,1.000000,-9.000000,0.00000,0.000000,0.000000,-9.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000,1.000000,4.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.00000,-99.000000,-99.000000,-9.000000,1.000000,-9.000000,1.000000,0.000000,1.000000,-9.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.000000,1.000000,-9.900000e+01,-9.000000,-99.000000,-99.000000,-99.000000,-99.000000,-9.000000,-9.900000e+01,-9.900000e+01,-9.900000e+01,-99.000000,1.000000,-99.000000,-9.000000,-9.000000,-9.000000,-9.000000
25%,1.991083e+11,1991.000000,4.000000,8.000000,0.000000,78.000000,6.000000,11.274796,7.052742,1.000000,0.000000,1.00000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,2.000000,2.000000,3.000000,22.000000,83.000000,4.000000,29.000000,74.000000,4.000000,34.000000,69.000000,0.000000,0.000000,0.000000,0.00000,-99.000000,0.000000,0.000000,6.000000,0.000000,6.000000,0.000000,4.000000,-9.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.000000,5.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,-9.900000e+01,0.000000,1.000000,0.000000,-99.000000,-99.000000,0.000000,0.000000e+00,0.000000e+00,-9.900000e+01,0.000000,2.000000,-99.000000,-9.000000,-9.000000,0.000000,-9.000000
50%,2.010031e+11,2010.000000,6.000000,15.000000,0.000000,98.000000,7.000000,31.445840,43.471427,1.000000,0.000000,1.00000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,2.000000,7.000000,4.000000,35.000000,100.000000,14.000000,67.000000,97.000000,14.000000,67.000000,104.000000,0.000000,0.000000,0.000000,0.00000,-99.000000,0.000000,0.000000,8.000000,0.000000,7.000000,0.000000,7.000000,-9.000000,6.000000,12.000000,6.000000,7.000000,6.000000,8.000000,6.000000,9.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,-9.900000e+01,0.000000,2.000000,0.000000,-99.000000,-99.000000,0.000000,1.500000e+04,0.000000e+00,0.000000e+00,0.000000,4.000000,0.000000,-9.000000,-9.000000,0.000000,0.000000
75%,2.015013e+11,2015.000000,9.000000,23.000000,0.000000,160.000000,10.000000,34.621521,68.783077,1.000000,0.000000,1.00000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,7.000000,7.000000,14.000000,74.000000,168.000000,14.000000,68.000000,182.000000,14.000000,73.000000,182.000000,0.000000,1.000000,0.000000,0.00000,-99.000000,0.000000,0.000000,8.000000,1.000000,10.000000,1.000000,9.000000,0.000000,6.000000,16.000000,8.000000,18.000000,9.000000,20.000000,6.000000,16.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000,1.000000,4.000000,-9.900000e+01,0.000000,4.000000,0.000000,0.000000,4.000000,0.000000,4.000000e+05,0.000000e+00,1.273412e+03,0.000000,7.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,2.018123e+11,2018.000000,12.000000,31.000000,1.000000,1004.000000,12.000000,74.633553,179.366667,5.000000,1.000000,1.00000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,9.000000,9.000000,8.000000,22.000000,113.000000,1004.000000,22.000000,113.000000,1004.000000,22.000000,113.000000,1004.000000,1.000000,1.000000,1.000000,1.00000,25000.000000,406.000000,1.000000,10.000000,1.000000,10.000000,1.000000,10.000000,1.000000,13.000000,31.000000,13.000000,31.000000,13.000000,28.000000,12.000000,28.000000,1570.000000,1361.000000,500.000000,10878.000000,751.000000,200.000000,1.000000,4.000000,2.700000e+09,1.000000,17000.000000,86.000000,999.000000,2676.000000,1.000000,1.000000e+09,1.320000e+08,2.750000e+08,48000.000000,7.000000,2912.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
# count entries for each variable
df.count()

eventid               191464
iyear                 191464
imonth                191464
iday                  191464
approxdate             10292
extended              191464
resolution              4453
country               191464
country_txt           191464
region                191464
region_txt            191464
provstate             191462
city                  191038
latitude              186884
longitude             186883
specificity           191463
vicinity              191464
location               60285
summary               125340
crit1                 191464
crit2                 191464
crit3                 191464
doubtterr             191464
alternative            31070
alternative_txt        31070
multiple              191464
success               191464
suicide               191464
attacktype1           191464
attacktype1_txt       191464
attacktype2             7023
attacktype2_txt         7023
attacktype3              485
attacktype3_txt          485
targtype1             191464
targtype1_txt         191464
targsubtype1          180465
targsubtype1_txt      180465
corp1                 148917
target1               190828
natlty1               189742
natlty1_txt           189742
targtype2              12196
targtype2_txt          12196
targsubtype2           11732
targsubtype2_txt       11732
corp2                  11169
target2                12072
natlty2                11879
natlty2_txt            11879
targtype3               1313
targtype3_txt           1313
targsubtype3            1234
targsubtype3_txt        1234
corp3                   1163
target3                 1312
natlty3                 1284
natlty3_txt             1284
gname                 191464
gsubname                6474
gname2                  2216
gsubname2                164
gname3                   356
gsubname3                 21
motive                 52230
guncertain1           191084
guncertain2             2158
guncertain3              352
individual            191464
nperps                120355
nperpcap              121981
claimed               125349
claimmode              21550
claimmode_txt          21550
claim2                  2093
claimmode2               664
claimmode2_txt           664
claim3                   350
claimmode3               134
claimmode3_txt           134
compclaim               4890
weaptype1             191464
weaptype1_txt         191464
weapsubtype1          169178
weapsubtype1_txt      169178
weaptype2              14192
weaptype2_txt          14192
weapsubtype2           12492
weapsubtype2_txt       12492
weaptype3               2034
weaptype3_txt           2034
weapsubtype3            1844
weapsubtype3_txt        1844
weaptype4                 73
weaptype4_txt             73
weapsubtype4              70
weapsubtype4_txt          70
weapdetail            116976
nkill                 180435
nkillus               127021
nkillter              124030
nwound                173905
nwoundus              126764
nwoundte              121594
property              191464
propextent             67286
propextent_txt         67286
propvalue              42196
propcomment            61177
ishostkid             191286
nhostkid               14626
nhostkidus             14571
nhours                  4381
ndays                   8861
divert                   331
kidhijcountry           3310
ransom                 78428
ransomamt               1416
ransomamtus              623
ransompaid               838
ransompaidus             611
ransomnote               544
hostkidoutcome         12045
hostkidoutcome_txt     12045
nreleased              11454
addnotes               30958
scite1                125278
scite2                 83237
scite3                 47220
dbsource              191464
INT_LOG               191464
INT_IDEO              191464
INT_MISC              191464
INT_ANY               191464
related                26698
dtype: int64

In [7]:
# check dataset size
df.shape

(191464, 135)

# Clean dataset

### Filter by date

In [8]:
# filter by date; events that occurred since 2012
df = df[df.iyear >= 2012]

# confirm filter worked as expected
print(f'Events occurred between {min(df.iyear)} and {max(df.iyear)}')

Events occurred between 2012 and 2018

In [9]:
# check dataset size
df.shape

(86668, 135)

### Filter by event type

Each incident may be one of multiple attack types, see p. 24 of codebook. Note that these events are assigned in a hierarchical order and at a maximum of three event types. For example, if one event included a hijacking, barricade, bombing, and unarmed assault, it would be recorded with attacktype1=2, attacktype2=4, attacktype3=5, and the unarmed assault would go unlisted. Here is the categorical breakdown for variable "attacktype1", "attacktype2", and "attacktype3".

1. Assassination
2. Hijacking
3. Kidnapping
4. Barricade Incident
5. Bombing/Explosion
6. Armed Assault
7. Unarmed Assault
8. Facility/Infrastructure Attack
9. Unknown

*Although we originally planned to filter on this variable, in my opinion, we probably don't need to. What I usually think of when I think of terrorism and travel is 5 (bombing) and 8 (facility/infrastructure attack), but any of these event types could have an impact on tourist interest, because they're all scary.*

Here is a breakdown of events by type:

In [10]:
df.attacktype1.value_counts()

3    43949
2    20146
6     6571
1     5603
9     4851
7     4467
8      471
5      371
4      239
Name: attacktype1, dtype: int64

In [11]:
df.attacktype2.value_counts()

2.0    2305
7.0    1589
3.0     182
6.0      40
8.0      25
5.0      12
1.0       1
Name: attacktype2, dtype: int64

In [12]:
df.attacktype3.value_counts()

7.0    225
2.0     71
8.0      1
Name: attacktype3, dtype: int64

In [13]:
# choose attack types to include
# include all attack types by setting to [1,2,3,4,5,6,7,8,9]
incident_types = [1,2,3,4,5,6,7,8,9]

# filter for incidents that include specified event type as primary, secondary or tertiary
df = df[df.attacktype1.isin(incident_types) |
        df.attacktype2.isin(incident_types) |
        df.attacktype3.isin(incident_types)]

In [14]:
# check dataset size
df.shape

(86668, 135)

### Filter for certainly terrorism

There is not always enough information available to determine whether an incident was definitively terrorism, "terrorosim proper", rather than another form of crime (e.g. organized crime, hate crime, insurgency); see p. 11 and 16 of codebook. Here is the categorical breakdown for variable "doutterr":

0. No. There is essentially no doubt as to whether the incident is an act of terrorism.
1. Yes. There is doubt as to whether the incident is an act of terrorism.

*I think we might want to filter based on this variable, for only events where there is no doubt (0). We are only interested in terrorism, not crime by other definitions.*

*The argument against filtering for it is that anything that seemed enough like terrorism to include in GTD at all, even with some doubt, may be sufficient for us.*

In [15]:
df.doubtterr.value_counts()

0    70261
1    16407
Name: doubtterr, dtype: int64

In [16]:
# choose whether to include only incidents where there is no doubt
remove_doubtful = False

if remove_doubtful:
    # filter for incidents that are definitively terrorism
    df = df[df.doubtterr == 0]

In [17]:
# check dataset size
df.shape

(86668, 135)

### Filter for "successful" terrorism

A terrorist incident is considered successful if there are tangible effects. It does not necessarily mean that it achieved the perpetrator's original goal. If any attack type has a tangible effect, then it is considered "successful"; except for assassinations, which are only considered successful if the inteded target is killed. See p. 26 of codebook. Here is the categorical breakdown for variable "success":

1. Yes. The incident was successful.
2. No. The incident was not successful.

*I think this will have an effect on our visualizations. My guess is that unsuccessful incidents (usually) have no wounded or killed. Thinking about our violin plots, including unsuccessful events may lead to a distribution that is a little bottom heavy. Just something to keep in mind!*

In [18]:
df.success.value_counts()

1    73547
0    13121
Name: success, dtype: int64

In [19]:
# choose whether to include only "successful" incidents
remove_unsuccessful = False

if remove_unsuccessful:
    # filter for incidents that are "successful"
    df = df[df.success == 1]

In [20]:
df.shape

(86668, 135)

### Create flag for tourist target types

The dataset contains information about targets/victims; see p.32 of codebook. Here are some potentially relevant categories for variables "targtype1", "targtype2", and "targtype3":

6. Airports & aircraft
8. Educational institution
18. Tourists
19. Transportation (other than aviation)

*I think this variable could be interesting. I added it to the terrorism_by_incident dataset, but not the terrorism_by_year dataset. Can change that, though.*

Here is a breakdown of events by target type:

In [21]:
df.targtype1.value_counts()

14    22796
4     17779
3     13559
2      7843
1      6007
20     5262
15     2278
8      1856
17     1817
19     1672
21     1639
10     1087
22      999
7       796
12      387
16      320
6       197
11       98
9        97
13       89
18       76
5        14
Name: targtype1, dtype: int64

In [22]:
df.targtype2.value_counts()

14.0    4099
4.0     1073
3.0      714
17.0     497
1.0      363
2.0      256
8.0      176
15.0      76
19.0      76
10.0      68
21.0      50
7.0       26
22.0      23
12.0      23
18.0      19
13.0      18
16.0      16
6.0       16
11.0      11
9.0        6
Name: targtype2, dtype: int64

In [23]:
df.targtype3.value_counts()

14.0    415
4.0      59
1.0      55
3.0      44
17.0     34
2.0      25
8.0      10
12.0      9
16.0      8
15.0      7
10.0      6
13.0      5
19.0      5
18.0      4
11.0      3
7.0       3
22.0      2
6.0       2
9.0       1
Name: targtype3, dtype: int64

In [24]:
# create flag for any tourist targets
df['targtour'] = (df.targtype1 == 8) | (df.targtype2 == 8) | (df.targtype3 == 8)

# Group by variables

### Collapse related incidents

If an event occurs at separate times or locations, than they are considered separate incidents; see p. 12 of codebook. "If any discontinuity in time or space is noted, the event is comprised of multiple incidents."

Relevant variables are "multiple", which indicates whether attacks are connected; see p. 17 of codebook. Here is the categorical breakdown for the variable multiple:

1. Yes. The attack is part of a multiple incident.
2. No. The attack is not part of a multiple incident.

If the attack is part of a multiple incident, the variable related "related" includes the text of event ID's from "eventid" for related incidents; see p. 13 and 17 of codebook.

In [25]:
df.shape

(86668, 136)

*The data dictionary includes many more columns, but to keep them and to aggregate related events will require some aggregation function for those other columns. If we want more columns, let's talk about the best way to aggregate them in this step!*

Here's an example for how to concatenate text; similar approach could be used for transforming other columns as well.

In [26]:
#df.groupby(['related','iyear','imonth','iday',
#            'country','country_txt','region',
#            'region_txt','provstate','city'])['summary'].apply(','.join)

Collapse events into one incident if records are related, occurred in the same city and on the same day. Numbers of victims are summed across records into a single incident.

In [27]:
# group related incidents that occur on same city and day
terrorism_by_incident = df.groupby(['related',
                                    'iyear','imonth','iday',
                                    'country','region',
                                    'country_txt','region_txt',
                                    'provstate','city']).agg(
    incident_id  = ('eventid', 'first'),
    nevents   = ('eventid', 'size'),
    doubtterr = ('doubtterr', 'sum'),
    success   = ('success', 'sum'),
    targtour  = ('targtour', 'sum'),
    nkill     = ('nkill', 'sum'),
    nkillus   = ('nkillus', 'sum'),
    nkillter  = ('nkillter', 'sum'),
    nwound    = ('nwound', 'sum'),
    nwoundus  = ('nwoundus', 'sum'),
    nwoundte  = ('nwoundte', 'sum')
)

# reset index
terrorism_by_incident.reset_index(inplace=True)
terrorism_by_incident.set_index('incident_id', inplace=True)

# rename columns
terrorism_by_incident = terrorism_by_incident.rename(columns={'iyear':'year_gtd',
                                                              'imonth':'month_gtd',
                                                              'iday':'day_gtd',
                                                              'country':'country_gtd',
                                                              'country_txt':'country_txt_gtd'})

# inspect dataframe
terrorism_by_incident.head()

,related,year_gtd,month_gtd,day_gtd,country_gtd,region,country_txt_gtd,region_txt,provstate,city,nevents,doubtterr,success,targtour,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte
incident_id,,,,,,,,,,,,,,,,,,,,
201201010002,"201201010002, 201201010004",2012,1,1,104,11,Kenya,Sub-Saharan Africa,North Eastern,Garissa,2,0,2,0,5.0,0.0,0.0,28.0,0.0,0.0
201201010013,"201201010013, 201201030040, 201201030041",2012,1,1,229,11,Democratic Republic of the Congo,Sub-Saharan Africa,South Kivu,Shabunda,1,0,1,0,18.0,0.0,0.0,5.0,0.0,0.0
201201030040,"201201010013, 201201030040, 201201030041",2012,1,3,229,11,Democratic Republic of the Congo,Sub-Saharan Africa,South Kivu,Shabunda,2,0,2,0,27.0,0.0,0.0,8.0,0.0,0.0
201201030008,"201201030008, 201201030009, 201201030010",2012,1,3,4,6,Afghanistan,South Asia,Kandahar,Kandahar,3,0,3,0,15.0,0.0,2.0,35.0,0.0,0.0
201201030019,"201201030019, 201201030020, 201201030021, 2012...",2012,1,1,217,1,United States,North America,New York,New York City,4,4,4,0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
# write to csv
terrorism_by_incident.to_csv('../data/derived/terrorism_by_incident.csv')

### Group by year

In [29]:
# group by year and country
terrorism_by_year = terrorism_by_incident.groupby(['year_gtd','country_gtd']).agg(
    incident_ct_total = ('country_gtd', 'size'), # arbitrarily chose to count one variable
    nkill_total       = ('nkill', 'sum'),
    nkillus_total     = ('nkillus', 'sum'),
    nkillter_total    = ('nkillter', 'sum'),
    nwound_total      = ('nwound', 'sum'),
    nwoundus_total    = ('nwoundus', 'sum'),
    nwoundte_total    = ('nwoundte', 'sum')
)

# inspect dataframe
terrorism_by_year.head()

                      incident_ct_total  nkill_total  nkillus_total  \
year_gtd country_gtd
2012     4                           73        292.0            4.0
         6                            1          0.0            0.0
         18                           2          2.0            0.0
         45                           6          2.0            0.0
         60                           2          0.0            0.0

                      nkillter_total  nwound_total  nwoundus_total  \
year_gtd country_gtd
2012     4                      90.0         631.0             2.0
         6                       0.0           1.0             0.0
         18                      0.0           1.0             0.0
         45                      0.0          22.0             0.0
         60                      0.0           3.0             0.0

                      nwoundte_total
year_gtd country_gtd
2012     4                       6.0
         6                       0.0
         18                      0.0
         45                      0.0
         60                      0.0

In [30]:
# write to csv
terrorism_by_year.to_csv('../data/derived/terrorism_by_year.csv')