# Import and setup

In [1]:
import pandas as pd

In [2]:
# change display options
pd.options.display.max_rows = 150
pd.options.display.max_columns = 150

In [3]:
%%time
# import terrorism data (may take a few minutes to load)
df = pd.read_excel('../data/raw/globalterrorismdb_0919dist.xlsx')

# Explore dataset

In [4]:
# look at sample of dataset
df.sample(5)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,region_txt,provstate,city,latitude,longitude,specificity,vicinity,location,summary,crit1,crit2,crit3,doubtterr,alternative,alternative_txt,multiple,success,suicide,attacktype1,attacktype1_txt,attacktype2,attacktype2_txt,attacktype3,attacktype3_txt,targtype1,targtype1_txt,targsubtype1,targsubtype1_txt,corp1,target1,natlty1,natlty1_txt,targtype2,targtype2_txt,targsubtype2,targsubtype2_txt,corp2,target2,natlty2,natlty2_txt,targtype3,targtype3_txt,targsubtype3,targsubtype3_txt,corp3,target3,natlty3,natlty3_txt,gname,gsubname,gname2,gsubname2,gname3,gsubname3,motive,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claimmode_txt,claim2,claimmode2,claimmode2_txt,claim3,claimmode3,claimmode3_txt,compclaim,weaptype1,weaptype1_txt,weapsubtype1,weapsubtype1_txt,weaptype2,weaptype2_txt,weapsubtype2,weapsubtype2_txt,weaptype3,weaptype3_txt,weapsubtype3,weapsubtype3_txt,weaptype4,weaptype4_txt,weapsubtype4,weapsubtype4_txt,weapdetail,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propextent_txt,propvalue,propcomment,ishostkid,nhostkid,nhostkidus,nhours,ndays,divert,kidhijcountry,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,ransomnote,hostkidoutcome,hostkidoutcome_txt,nreleased,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
8892,197907110003,1979,7,11,NaN,0,NaT,94,Iran,10,Middle East & North Africa,Unknown,Unknown,NaN,NaN,5.0,0,NaN,NaN,1,1,1,-9,NaN,NaN,0,1,0,2,Armed Assault,NaN,NaN,NaN,NaN,3,Police,22.0,"Police Building (headquarters, station, school)",NaN,Guard post,94.0,Iran,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,Firearms,2.0,Automatic or Semi-Automatic Rifle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Automatic firearm,0.0,NaN,NaN,0.0,NaN,NaN,1,4.0,Unknown,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9,-9,0,-9,NaN
77419,200501100005,2005,1,10,NaN,0,NaT,153,Pakistan,6,South Asia,Balochistan,Mastung,29.803965,66.850990,1.0,0,NaN,01/10/2005: Three young brothers died when the...,1,1,1,1,2.0,Other Crime Type,0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,14,Private Citizens & Property,67.0,Unnamed Civilian/Unspecified,Civilan(s),Civilians in Mastung,153.0,Pakistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,Unknown,0.0,NaN,NaN,0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,Explosives,16.0,Unknown Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The explosives were concealed in a box.,3.0,0.0,0.0,2.0,0.0,0.0,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""Exploding Box Kills Three Pakistani Children,...",NaN,NaN,CETIS,-9,-9,0,-9,NaN
43783,199008220005,1990,8,22,NaN,0,NaT,159,Peru,3,South America,Junin,Huancayo district,-12.068306,-75.210163,3.0,0,NaN,NaN,1,1,1,0,NaN,NaN,0,1,0,1,Assassination,NaN,NaN,NaN,NaN,14,Private Citizens & Property,68.0,Named Civilian,NaN,Andres Porras,159.0,Peru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shining Path (SL),NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,Firearms,3.0,Handgun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pistol,1.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
91135,200903190003,2009,3,19,NaN,0,NaT,4,Afghanistan,6,South Asia,Helmand,Lashkar Gah,31.600630,64.369652,1.0,0,"The attack took place in Lashgar Gah, Helmand...","03/19/2009: On Thursday, around noon at 1300 i...",1,1,1,0,NaN,NaN,0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,2,Government (General),18.0,"Government Personnel (excluding police, military)",Afghanistan Government,The vehicle of an Afghan Parliament member,4.0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Taliban,NaN,NaN,NaN,NaN,NaN,The specific motive for the attack is unknown.,1.0,NaN,NaN,0,-99.0,0.0,1.0,10.0,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,Explosives,17.0,Other Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,An improvised explosive device was used in the...,5.0,0.0,0.0,1.0,0.0,0.0,1,4.0,Unknown,NaN,The attack caused an unknown amount of propert...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Xinhua News Agency, ""Roadside Bomb Kills MP Al...","Yahoo News, ""Bomb Kills Afghan MP, Four Others...","National Counterterrorism Center, ""Four Privat...",ISVG,0,0,0,0,NaN
945,197107280001,1971,7,28,NaN,0,NaT,11,Argentina,3,South America,Cordoba,Cordoba,-31.399301,-64.182129,1.0,0,NaN,NaN,1,1,1,0,NaN,NaN,0,1,0,1,Assassination,NaN,NaN,NaN,NaN,4,Military,34.0,"Military Personnel (soldiers, troops, officers...",Cordoba-Arg. Govt,"Retd Army Officer, director of Prisons in Cord...",11.0,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Peronist Armed Forces (FAP),NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN

In [5]:
# describe dataset
df.describe()

,eventid,iyear,imonth,iday,extended,country,region,latitude,longitude,specificity,vicinity,crit1,crit2,crit3,doubtterr,alternative,multiple,success,suicide,attacktype1,attacktype2,attacktype3,targtype1,targsubtype1,natlty1,targtype2,targsubtype2,natlty2,targtype3,targsubtype3,natlty3,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claim2,claimmode2,claim3,claimmode3,compclaim,weaptype1,weapsubtype1,weaptype2,weapsubtype2,weaptype3,weapsubtype3,weaptype4,weapsubtype4,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propvalue,ishostkid,nhostkid,nhostkidus,nhours,ndays,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,hostkidoutcome,nreleased,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
count,1.914640e+05,191464.000000,191464.000000,191464.000000,191464.000000,191464.000000,191464.000000,186884.000000,186883.000000,191463.000000,191464.000000,191464.00000,191464.000000,191464.000000,191464.000000,31070.000000,191464.000000,191464.000000,191464.000000,191464.000000,7023.000000,485.000000,191464.000000,180465.000000,189742.000000,12196.000000,11732.000000,11879.000000,1313.000000,1234.000000,1284.000000,191084.000000,2158.000000,352.000000,191464.00000,120355.000000,121981.000000,125349.000000,21550.000000,2093.000000,664.000000,350.000000,134.000000,4890.000000,191464.000000,169178.000000,14192.000000,12492.000000,2034.000000,1844.000000,73.000000,70.000000,180435.000000,127021.000000,124030.000000,173905.000000,126764.000000,121594.000000,191464.000000,67286.000000,4.219600e+04,191286.000000,14626.000000,14571.000000,4381.000000,8861.000000,78428.000000,1.416000e+03,6.230000e+02,8.380000e+02,611.000000,12045.000000,11454.000000,191464.000000,191464.000000,191464.000000,191464.000000
mean,2.003486e+11,2003.420136,6.462510,15.507688,0.047476,131.290446,7.205167,23.462121,28.902126,1.458172,0.069151,0.98841,0.993127,0.872838,-0.485757,1.297039,0.139415,0.886825,0.036618,3.276099,3.809056,5.327835,8.449259,46.976367,127.285509,10.167842,55.005114,128.984847,10.113481,55.771475,141.047508,0.079285,0.269694,0.201705,0.00351,-66.502140,-1.436117,0.065497,7.055452,0.246536,7.222892,0.377143,6.701493,-6.230061,6.472141,11.101709,6.853086,10.918268,6.971976,11.862256,6.246575,10.842857,2.410735,0.043079,0.529186,3.161232,0.037526,0.118600,-0.629319,3.291978,1.932884e+05,0.056842,4.087447,-0.334912,-49.963422,-33.179664,-0.154384,3.057619e+06,5.227734e+05,6.961705e+05,217.004910,4.643005,-29.816309,-4.521727,-4.439247,0.088951,-3.930582
std,1.334949e+09,13.349405,3.388515,8.807727,0.212656,112.058063,2.923811,18.405309,57.231040,0.991536,0.284292,0.10703,0.082621,0.333156,2.399609,0.723066,0.346380,0.316808,0.187822,1.947979,2.307806,2.234623,6.640723,30.833421,89.795208,5.709859,25.612896,124.532178,5.689909,26.114098,162.385505,0.270183,0.443904,0.401844,0.05914,208.104397,12.504317,1.058084,2.403405,0.934977,2.718301,0.485365,2.883789,4.268216,2.207859,6.494063,2.292732,7.642624,2.191003,8.575762,1.507212,8.192672,11.445411,5.461232,4.339206,42.679122,2.949192,1.544178,3.212640,0.484213,1.492315e+07,0.499810,195.153254,6.635037,80.908500,125.390956,1.240840,2.951278e+07,6.730057e+06,9.792528e+06,2796.042504,2.034429,65.183303,4.543713,4.639931,0.556741,4.689726
min,1.970000e+11,1970.000000,0.000000,0.000000,0.000000,4.000000,1.000000,-53.154613,-176.176447,1.000000,-9.000000,0.00000,0.000000,0.000000,-9.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000,1.000000,4.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.00000,-99.000000,-99.000000,-9.000000,1.000000,-9.000000,1.000000,0.000000,1.000000,-9.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.000000,1.000000,-9.900000e+01,-9.000000,-99.000000,-99.000000,-99.000000,-99.000000,-9.000000,-9.900000e+01,-9.900000e+01,-9.900000e+01,-99.000000,1.000000,-99.000000,-9.000000,-9.000000,-9.000000,-9.000000
25%,1.991083e+11,1991.000000,4.000000,8.000000,0.000000,78.000000,6.000000,11.274796,7.052742,1.000000,0.000000,1.00000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,2.000000,2.000000,3.000000,22.000000,83.000000,4.000000,29.000000,74.000000,4.000000,34.000000,69.000000,0.000000,0.000000,0.000000,0.00000,-99.000000,0.000000,0.000000,6.000000,0.000000,6.000000,0.000000,4.000000,-9.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.000000,5.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,-9.900000e+01,0.000000,1.000000,0.000000,-99.000000,-99.000000,0.000000,0.000000e+00,0.000000e+00,-9.900000e+01,0.000000,2.000000,-99.000000,-9.000000,-9.000000,0.000000,-9.000000
50%,2.010031e+11,2010.000000,6.000000,15.000000,0.000000,98.000000,7.000000,31.445840,43.471427,1.000000,0.000000,1.00000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,2.000000,7.000000,4.000000,35.000000,100.000000,14.000000,67.000000,97.000000,14.000000,67.000000,104.000000,0.000000,0.000000,0.000000,0.00000,-99.000000,0.000000,0.000000,8.000000,0.000000,7.000000,0.000000,7.000000,-9.000000,6.000000,12.000000,6.000000,7.000000,6.000000,8.000000,6.000000,9.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,-9.900000e+01,0.000000,2.000000,0.000000,-99.000000,-99.000000,0.000000,1.500000e+04,0.000000e+00,0.000000e+00,0.000000,4.000000,0.000000,-9.000000,-9.000000,0.000000,0.000000
75%,2.015013e+11,2015.000000,9.000000,23.000000,0.000000,160.000000,10.000000,34.621521,68.783077,1.000000,0.000000,1.00000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,7.000000,7.000000,14.000000,74.000000,168.000000,14.000000,68.000000,182.000000,14.000000,73.000000,182.000000,0.000000,1.000000,0.000000,0.00000,-99.000000,0.000000,0.000000,8.000000,1.000000,10.000000,1.000000,9.000000,0.000000,6.000000,16.000000,8.000000,18.000000,9.000000,20.000000,6.000000,16.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000,1.000000,4.000000,-9.900000e+01,0.000000,4.000000,0.000000,0.000000,4.000000,0.000000,4.000000e+05,0.000000e+00,1.273412e+03,0.000000,7.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,2.018123e+11,2018.000000,12.000000,31.000000,1.000000,1004.000000,12.000000,74.633553,179.366667,5.000000,1.000000,1.00000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,9.000000,9.000000,8.000000,22.000000,113.000000,1004.000000,22.000000,113.000000,1004.000000,22.000000,113.000000,1004.000000,1.000000,1.000000,1.000000,1.00000,25000.000000,406.000000,1.000000,10.000000,1.000000,10.000000,1.000000,10.000000,1.000000,13.000000,31.000000,13.000000,31.000000,13.000000,28.000000,12.000000,28.000000,1570.000000,1361.000000,500.000000,10878.000000,751.000000,200.000000,1.000000,4.000000,2.700000e+09,1.000000,17000.000000,86.000000,999.000000,2676.000000,1.000000,1.000000e+09,1.320000e+08,2.750000e+08,48000.000000,7.000000,2912.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
# count entries for each variable
df.count()

eventid               191464
iyear                 191464
imonth                191464
iday                  191464
approxdate             10292
extended              191464
resolution              4453
country               191464
country_txt           191464
region                191464
region_txt            191464
provstate             191462
city                  191038
latitude              186884
longitude             186883
specificity           191463
vicinity              191464
location               60285
summary               125340
crit1                 191464
crit2                 191464
crit3                 191464
doubtterr             191464
alternative            31070
alternative_txt        31070
multiple              191464
success               191464
suicide               191464
attacktype1           191464
attacktype1_txt       191464
attacktype2             7023
attacktype2_txt         7023
attacktype3              485
attacktype3_txt          485
targtype1             191464
targtype1_txt         191464
targsubtype1          180465
targsubtype1_txt      180465
corp1                 148917
target1               190828
natlty1               189742
natlty1_txt           189742
targtype2              12196
targtype2_txt          12196
targsubtype2           11732
targsubtype2_txt       11732
corp2                  11169
target2                12072
natlty2                11879
natlty2_txt            11879
targtype3               1313
targtype3_txt           1313
targsubtype3            1234
targsubtype3_txt        1234
corp3                   1163
target3                 1312
natlty3                 1284
natlty3_txt             1284
gname                 191464
gsubname                6474
gname2                  2216
gsubname2                164
gname3                   356
gsubname3                 21
motive                 52230
guncertain1           191084
guncertain2             2158
guncertain3              352
individual            191464
nperps                120355
nperpcap              121981
claimed               125349
claimmode              21550
claimmode_txt          21550
claim2                  2093
claimmode2               664
claimmode2_txt           664
claim3                   350
claimmode3               134
claimmode3_txt           134
compclaim               4890
weaptype1             191464
weaptype1_txt         191464
weapsubtype1          169178
weapsubtype1_txt      169178
weaptype2              14192
weaptype2_txt          14192
weapsubtype2           12492
weapsubtype2_txt       12492
weaptype3               2034
weaptype3_txt           2034
weapsubtype3            1844
weapsubtype3_txt        1844
weaptype4                 73
weaptype4_txt             73
weapsubtype4              70
weapsubtype4_txt          70
weapdetail            116976
nkill                 180435
nkillus               127021
nkillter              124030
nwound                173905
nwoundus              126764
nwoundte              121594
property              191464
propextent             67286
propextent_txt         67286
propvalue              42196
propcomment            61177
ishostkid             191286
nhostkid               14626
nhostkidus             14571
nhours                  4381
ndays                   8861
divert                   331
kidhijcountry           3310
ransom                 78428
ransomamt               1416
ransomamtus              623
ransompaid               838
ransompaidus             611
ransomnote               544
hostkidoutcome         12045
hostkidoutcome_txt     12045
nreleased              11454
addnotes               30958
scite1                125278
scite2                 83237
scite3                 47220
dbsource              191464
INT_LOG               191464
INT_IDEO              191464
INT_MISC              191464
INT_ANY               191464
related                26698
dtype: int64

In [7]:
# check dataset size
df.shape

(191464, 135)

# Clean dataset

### Filter by date

In [8]:
# filter by date; events that occurred since 2012
df = df[df.iyear >= 2012]

# confirm filter worked as expected
print(f'Events occurred between {min(df.iyear)} and {max(df.iyear)}')

Events occurred between 2012 and 2018

In [9]:
# check dataset size
df.shape

(86668, 135)

### Filter for certainly terrorism

There is not always enough information available to determine whether an incident was definitively terrorism, "terrorism proper", rather than another form of crime (e.g. organized crime, hate crime, insurgency); see p. 11 and 16 of codebook. Here is the categorical breakdown for variable `doutterr`:

* 0 - No. There is essentially no doubt as to whether the incident is an act of terrorism.
* 1 - Yes. There is doubt as to whether the incident is an act of terrorism.

In [13]:
df.doubtterr.value_counts()

0    70261
1    16407
Name: doubtterr, dtype: int64

In [14]:
# choose whether to include only incidents where there is no doubt
remove_doubtful = True

if remove_doubtful:
    # filter for incidents that are definitively terrorism
    df = df[df.doubtterr == 0]

In [15]:
# check dataset size
df.shape

(70261, 135)

### Filter for "successful" terrorism

A terrorist incident is considered successful if there are tangible effects. It does not necessarily mean that it achieved the perpetrator's original goal. If any attack type has a tangible effect, then it is considered "successful"; except for assassinations, which are only considered successful if the inteded target is killed. See p. 26 of codebook. Here is the categorical breakdown for variable `success`:

* 0 - No. The incident was not successful.
* 1 - Yes. The incident was successful.

In [16]:
df.success.value_counts()

1    59395
0    10866
Name: success, dtype: int64

In [17]:
# choose whether to include only "successful" incidents
remove_unsuccessful = True

if remove_unsuccessful:
    # filter for incidents that are "successful"
    df = df[df.success == 1]

In [18]:
df.shape

(59395, 135)

### Potential filter: event type

Each incident may be one of multiple attack types, see p. 24 of codebook. Note that these events are assigned in a hierarchical order (different from variable order below) and at a maximum of three event types. For example, if one event included a hijacking, barricade, bombing, and unarmed assault, it would be recorded with `attacktype1`=2, `attacktype2`=4, `attacktype3`=5, and the unarmed assault would go unlisted. Here is the categorical breakdown for variable `attacktype1`, `attacktype2`, and `attacktype3`.

* 1 - Assassination
* 2 - Armed Assault
* 3 - Bombing/Explosion
* 4 - Hijacking
* 5 - Barricade Incident
* 6 - Kidnapping
* 7 - Facility/Infrastructure Attack
* 8 - Unarmed Assault
* 9 - Unknown

Here is a breakdown of events by type:

In [10]:
pd.DataFrame({'attacktype1':df.attacktype1.value_counts(),
              'attacktype2':df.attacktype2.value_counts(),
              'attacktype3':df.attacktype3.value_counts()})

     attacktype1  attacktype2  attacktype3
1.0         5603          1.0          NaN
2.0        20146       2305.0         71.0
3.0        43949        182.0          NaN
4.0          239          NaN          NaN
5.0          371         12.0          NaN
6.0         6571         40.0          NaN
7.0         4467       1589.0        225.0
8.0          471         25.0          1.0
9.0         4851          NaN          NaN

In [11]:
# choose attack types to include
# include all attack types by setting to [1,2,3,4,5,6,7,8,9]
incident_types = [1,2,3,4,5,6,7,8,9]

# filter for incidents that include specified event type as primary, secondary or tertiary
df = df[df.attacktype1.isin(incident_types) |
        df.attacktype2.isin(incident_types) |
        df.attacktype3.isin(incident_types)]

In [12]:
# check dataset size
df.shape

(86668, 135)

### Potential fitler: target types

The dataset contains information about targets/victims; see p.32 of codebook. Here are some potentially relevant categories for variables `targtype1`, `targtype2`, and `targtype3`:

* 6 - Airports & aircraft
* 8 - Educational institution
* 18 - Tourists
* 19 - Transportation (other than aviation)

Here is a breakdown of events by target type:

In [19]:
pd.DataFrame({'targtype1':df.targtype1.value_counts(),
              'targtype2':df.targtype2.value_counts(),
              'targtype3':df.targtype3.value_counts()})

      targtype1  targtype2  targtype3
1.0        5453      334.0       52.0
2.0        6046      214.0       19.0
3.0       11969      583.0       36.0
4.0        2849      615.0       43.0
5.0          10        NaN        NaN
6.0         140       12.0        2.0
7.0         672       24.0        2.0
8.0        1610      164.0       10.0
9.0          87        5.0        1.0
10.0        828       58.0        6.0
11.0         74        9.0        2.0
12.0        356       21.0        7.0
13.0         76       15.0        5.0
14.0      20482     3821.0      386.0
15.0       2004       71.0        6.0
16.0        303       15.0        7.0
17.0       1464      373.0       25.0
18.0         68       19.0        4.0
19.0       1399       70.0        4.0
20.0       1375        NaN        NaN
21.0       1468       44.0        NaN
22.0        662       15.0        1.0

### Add columns

### Recast data types

In [62]:
# find text columns
text_columns_indices = ['_txt' in c for c in df.columns]

# create dictionary of text column name and 'string'
text_columns = df.columns[text_columns_indices]
text_type = ['string' for c in text_columns]
text_convert_dict = dict(zip(text_columns, text_type))

# preview dictionary
text_convert_dict

{'country_txt': 'string',
 'region_txt': 'string',
 'alternative_txt': 'string',
 'attacktype1_txt': 'string',
 'attacktype2_txt': 'string',
 'attacktype3_txt': 'string',
 'targtype1_txt': 'string',
 'targsubtype1_txt': 'string',
 'natlty1_txt': 'string',
 'targtype2_txt': 'string',
 'targsubtype2_txt': 'string',
 'natlty2_txt': 'string',
 'targtype3_txt': 'string',
 'targsubtype3_txt': 'string',
 'natlty3_txt': 'string',
 'claimmode_txt': 'string',
 'claimmode2_txt': 'string',
 'claimmode3_txt': 'string',
 'weaptype1_txt': 'string',
 'weapsubtype1_txt': 'string',
 'weaptype2_txt': 'string',
 'weapsubtype2_txt': 'string',
 'weaptype3_txt': 'string',
 'weapsubtype3_txt': 'string',
 'weaptype4_txt': 'string',
 'weapsubtype4_txt': 'string',
 'propextent_txt': 'string',
 'hostkidoutcome_txt': 'string'}

In [64]:
# convert text from object to string
df = df.astype(text_convert_dict)

In [65]:
# check new data types to ensure successful conversion
df.dtypes

eventid                        int64
iyear                          int64
imonth                         int64
iday                           int64
approxdate                    object
extended                       int64
resolution            datetime64[ns]
country                        int64
country_txt                   string
region                         int64
region_txt                    string
provstate                     object
city                          object
latitude                     float64
longitude                    float64
specificity                  float64
vicinity                       int64
location                      object
summary                       object
crit1                          int64
crit2                          int64
crit3                          int64
doubtterr                      int64
alternative                  float64
alternative_txt               string
multiple                       int64
success                        int64
suicide                        int64
attacktype1                    int64
attacktype1_txt               string
attacktype2                  float64
attacktype2_txt               string
attacktype3                  float64
attacktype3_txt               string
targtype1                      int64
targtype1_txt                 string
targsubtype1                 float64
targsubtype1_txt              string
corp1                         object
target1                       object
natlty1                      float64
natlty1_txt                   string
targtype2                    float64
targtype2_txt                 string
targsubtype2                 float64
targsubtype2_txt              string
corp2                         object
target2                       object
natlty2                      float64
natlty2_txt                   string
targtype3                    float64
targtype3_txt                 string
targsubtype3                 float64
targsubtype3_txt              string
corp3                         object
target3                       object
natlty3                      float64
natlty3_txt                   string
gname                         object
gsubname                      object
gname2                        object
gsubname2                     object
gname3                        object
gsubname3                     object
motive                        object
guncertain1                  float64
guncertain2                  float64
guncertain3                  float64
individual                     int64
nperps                       float64
nperpcap                     float64
claimed                      float64
claimmode                    float64
claimmode_txt                 string
claim2                       float64
claimmode2                   float64
claimmode2_txt                string
claim3                       float64
claimmode3                   float64
claimmode3_txt                string
compclaim                    float64
weaptype1                      int64
weaptype1_txt                 string
weapsubtype1                 float64
weapsubtype1_txt              string
weaptype2                    float64
weaptype2_txt                 string
weapsubtype2                 float64
weapsubtype2_txt              string
weaptype3                    float64
weaptype3_txt                 string
weapsubtype3                 float64
weapsubtype3_txt              string
weaptype4                    float64
weaptype4_txt                 string
weapsubtype4                 float64
weapsubtype4_txt              string
weapdetail                    object
nkill                        float64
nkillus                      float64
nkillter                     float64
nwound                       float64
nwoundus                     float64
nwoundte                     float64
property                       int64
propextent                   float64
propextent_txt                string
propvalue                    float64
propcomment                   object
ishostkid                    float64
nhostkid                     float64
nhostkidus                   float64
nhours                       float64
ndays                        float64
divert                        object
kidhijcountry                 object
ransom                       float64
ransomamt                    float64
ransomamtus                  float64
ransompaid                   float64
ransompaidus                 float64
ransomnote                    object
hostkidoutcome               float64
hostkidoutcome_txt            string
nreleased                    float64
addnotes                      object
scite1                        object
scite2                        object
scite3                        object
dbsource                      object
INT_LOG                        int64
INT_IDEO                       int64
INT_MISC                       int64
INT_ANY                        int64
related                       object
dtype: object

### Rename columns

# Save dataset

Here are a few last explorations, provided for comparison to the original import of this dataset above.

In [36]:
df.sample(5)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,region_txt,provstate,city,latitude,longitude,specificity,vicinity,location,summary,crit1,crit2,crit3,doubtterr,alternative,alternative_txt,multiple,success,suicide,attacktype1,attacktype1_txt,attacktype2,attacktype2_txt,attacktype3,attacktype3_txt,targtype1,targtype1_txt,targsubtype1,targsubtype1_txt,corp1,target1,natlty1,natlty1_txt,targtype2,targtype2_txt,targsubtype2,targsubtype2_txt,corp2,target2,natlty2,natlty2_txt,targtype3,targtype3_txt,targsubtype3,targsubtype3_txt,corp3,target3,natlty3,natlty3_txt,gname,gsubname,gname2,gsubname2,gname3,gsubname3,motive,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claimmode_txt,claim2,claimmode2,claimmode2_txt,claim3,claimmode3,claimmode3_txt,compclaim,weaptype1,weaptype1_txt,weapsubtype1,weapsubtype1_txt,weaptype2,weaptype2_txt,weapsubtype2,weapsubtype2_txt,weaptype3,weaptype3_txt,weapsubtype3,weapsubtype3_txt,weaptype4,weaptype4_txt,weapsubtype4,weapsubtype4_txt,weapdetail,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propextent_txt,propvalue,propcomment,ishostkid,nhostkid,nhostkidus,nhours,ndays,divert,kidhijcountry,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,ransomnote,hostkidoutcome,hostkidoutcome_txt,nreleased,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
144087,201502060094,2015,2,6,NaN,0,NaT,78,Greece,8,Western Europe,Attica,Athens,37.997492,23.762727,1.0,0,The incident occurred in the Exarchia neighbor...,02/06/2015: Assailants threw incendiary device...,1,1,1,0,NaN,NaN,0,1,0,2,Armed Assault,NaN,NaN,NaN,NaN,3,Police,23.0,Police Patrol (including vehicles and convoys),Road Traffic Police,Car,78.0,Greece,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,-99.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,Incendiary,19.0,Molotov Cocktail/Petrol Bomb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Molotov cocktails were used in the attack.,0.0,0.0,0.0,0.0,0.0,0.0,1,3.0,Minor (likely < $1 million),-99.0,A police vehicle was damaged in this attack.,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""Cars torched in Athens,"" Kathimerini, Februar...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN

In [37]:
df.describe()

,eventid,iyear,imonth,iday,extended,country,region,latitude,longitude,specificity,vicinity,crit1,crit2,crit3,doubtterr,alternative,multiple,success,suicide,attacktype1,attacktype2,attacktype3,targtype1,targsubtype1,natlty1,targtype2,targsubtype2,natlty2,targtype3,targsubtype3,natlty3,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claim2,claimmode2,claim3,claimmode3,compclaim,weaptype1,weapsubtype1,weaptype2,weapsubtype2,weaptype3,weapsubtype3,weaptype4,weapsubtype4,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propvalue,ishostkid,nhostkid,nhostkidus,nhours,ndays,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,hostkidoutcome,nreleased,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
count,5.939500e+04,59395.000000,59395.000000,59395.000000,59395.000000,59395.000000,59395.000000,59073.000000,59073.000000,59395.000000,59395.000000,59395.0,59395.0,59395.000000,59395.0,0.0,59395.000000,59395.0,59395.000000,59395.000000,3273.000000,264.000000,59395.000000,57495.000000,58853.000000,6482.000000,6440.000000,6470.000000,618.000000,608.000000,617.000000,59395.000000,1144.000000,189.000000,59395.000000,59395.000000,59394.000000,59395.000000,11305.000000,1144.000000,316.000000,189.000000,50.000000,315.000000,59395.000000,54417.000000,5688.000000,5057.000000,975.000000,901.000000,0.0,0.0,56395.000000,59386.000000,58632.000000,54179.000000,59366.000000,57882.000000,59395.000000,25387.000000,2.538700e+04,59395.000000,6510.000000,6510.000000,1858.000000,4653.000000,6509.000000,4.230000e+02,4.160000e+02,4.220000e+02,415.000000,6510.000000,6511.00000,59395.000000,59395.000000,59395.000000,59395.000000
mean,2.014974e+11,2014.907837,6.418806,15.651688,0.083761,118.883391,8.211011,25.860767,50.578677,1.460005,0.062850,1.0,1.0,0.999848,0.0,NaN,0.196633,1.0,0.051637,3.508393,4.385273,5.867424,9.187642,50.732429,121.335361,11.070657,58.615062,119.982689,11.192557,58.791118,139.003241,0.052176,0.236888,0.142857,0.004613,-79.230828,-0.314072,0.190336,6.970456,0.276224,7.221519,0.264550,6.480000,0.790476,6.454971,11.609295,7.274086,12.432074,7.318974,13.661487,NaN,NaN,2.592535,0.005237,0.463399,3.539213,0.007631,0.115200,-1.282111,3.155473,1.565988e+04,0.069450,3.127650,-0.079263,-81.196851,-40.341930,-0.379321,2.869062e+06,3.406481e+05,7.757170e+05,23.380723,4.773886,-34.75119,-4.845290,-4.725768,0.053843,-4.468272
std,1.811371e+08,1.812226,3.396340,8.787374,0.277032,92.128598,2.364788,13.249079,33.851031,0.877327,0.242696,0.0,0.0,0.012309,0.0,NaN,0.397456,0.0,0.221296,1.907589,2.455669,2.102289,6.467436,30.788343,89.675362,5.290827,23.909003,111.645472,5.179765,24.326191,177.701970,0.222384,0.425359,0.350857,0.067764,56.976964,6.304487,0.392569,2.094506,0.447324,2.330266,0.442265,2.314462,0.407616,2.133521,6.074028,2.420521,7.958791,2.124899,8.874292,NaN,NaN,10.620658,0.226306,4.126733,13.194974,0.346112,1.433554,3.764266,0.365825,9.898679e+05,0.682776,89.542073,3.010585,39.016439,118.186757,1.978855,1.771314e+07,6.480424e+06,1.345249e+07,490.987716,2.011916,67.39749,4.520883,4.658527,0.225709,4.696157
min,2.012010e+11,2012.000000,1.000000,1.000000,0.000000,4.000000,1.000000,-42.250458,-124.217890,1.000000,0.000000,1.0,1.0,0.000000,0.0,NaN,0.000000,1.0,0.000000,1.000000,2.000000,2.000000,1.000000,1.000000,4.000000,1.000000,1.000000,4.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,-99.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.000000,2.000000,-9.900000e+01,-9.000000,-99.000000,-99.000000,-99.000000,-99.000000,-9.000000,-9.900000e+01,-9.900000e+01,-9.900000e+01,-99.000000,1.000000,-99.00000,-9.000000,-9.000000,0.000000,-9.000000
25%,2.014010e+11,2014.000000,4.000000,8.000000,0.000000,92.000000,6.000000,14.652778,37.210418,1.000000,0.000000,1.0,1.0,1.000000,0.0,NaN,0.000000,1.0,0.000000,2.000000,2.000000,7.000000,3.000000,23.000000,92.000000,4.000000,34.000000,60.000000,8.000000,47.750000,44.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,0.000000,0.000000,7.000000,0.000000,7.000000,0.000000,4.000000,1.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,-9.900000e+01,0.000000,1.000000,0.000000,-99.000000,-99.000000,0.000000,-9.900000e+01,0.000000e+00,-9.900000e+01,0.000000,2.000000,-99.00000,-9.000000,-9.000000,0.000000,-9.000000
50%,2.015041e+11,2015.000000,6.000000,15.000000,0.000000,95.000000,10.000000,32.342871,44.542537,1.000000,0.000000,1.0,1.0,1.000000,0.0,NaN,0.000000,1.0,0.000000,3.000000,3.000000,7.000000,11.000000,53.000000,95.000000,14.000000,67.000000,95.000000,14.000000,67.000000,104.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,0.000000,0.000000,7.000000,0.000000,7.000000,0.000000,7.000000,1.000000,6.000000,12.000000,8.000000,16.000000,8.000000,18.000000,NaN,NaN,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,3.000000,-9.900000e+01,0.000000,2.000000,0.000000,-99.000000,-99.000000,0.000000,1.665307e+04,0.000000e+00,-9.900000e+01,0.000000,5.000000,0.00000,-9.000000,-9.000000,0.000000,-9.000000
75%,2.016103e+11,2016.000000,9.000000,23.000000,0.000000,153.000000,10.000000,34.111364,69.259349,2.000000,0.000000,1.0,1.0,1.000000,0.0,NaN,0.000000,1.0,0.000000,3.000000,7.000000,7.000000,14.000000,75.000000,158.000000,14.000000,68.000000,173.000000,14.000000,73.000000,182.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,0.000000,0.000000,8.000000,1.000000,9.000000,1.000000,8.000000,1.000000,6.000000,16.000000,9.000000,18.000000,9.000000,23.000000,NaN,NaN,2.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,3.000000,-9.900000e+01,0.000000,5.000000,0.000000,-99.000000,3.000000,0.000000,2.094781e+05,0.000000e+00,0.000000e+00,0.000000,7.000000,1.00000,0.000000,0.000000,0.000000,0.000000
max,2.018123e+11,2018.000000,12.000000,31.000000,1.000000,1004.000000,12.000000,69.983791,176.986756,5.000000,1.000000,1.0,1.0,1.000000,0.0,NaN,1.000000,1.0,1.000000,9.000000,8.000000,8.000000,22.000000,113.000000,1004.000000,22.000000,113.000000,1004.000000,22.000000,113.000000,1004.000000,1.000000,1.000000,1.000000,1.000000,5000.000000,100.000000,1.000000,10.000000,1.000000,10.000000,1.000000,10.000000,1.000000,13.000000,31.000000,13.000000,31.000000,13.000000,27.000000,NaN,NaN,953.000000,44.000000,326.000000,1500.000000,48.000000,100.000000,1.000000,4.000000,1.000000e+08,1.000000,5350.000000,9.000000,23.000000,2676.000000,1.000000,2.000000e+08,1.320000e+08,2.750000e+08,10000.000000,7.000000,2912.00000,1.000000,1.000000,1.000000,1.000000

In [38]:
df.count()

eventid               59395
iyear                 59395
imonth                59395
iday                  59395
approxdate             5982
extended              59395
resolution             1994
country               59395
country_txt           59395
region                59395
region_txt            59395
provstate             59394
city                  59395
latitude              59073
longitude             59073
specificity           59395
vicinity              59395
location              26965
summary               59395
crit1                 59395
crit2                 59395
crit3                 59395
doubtterr             59395
alternative               0
alternative_txt           0
multiple              59395
success               59395
suicide               59395
attacktype1           59395
attacktype1_txt       59395
attacktype2            3273
attacktype2_txt        3273
attacktype3             264
attacktype3_txt         264
targtype1             59395
targtype1_txt         59395
targsubtype1          57495
targsubtype1_txt      57495
corp1                 59395
target1               59395
natlty1               58853
natlty1_txt           58853
targtype2              6482
targtype2_txt          6482
targsubtype2           6440
targsubtype2_txt       6440
corp2                  6483
target2                6483
natlty2                6470
natlty2_txt            6470
targtype3               618
targtype3_txt           618
targsubtype3            608
targsubtype3_txt        608
corp3                   618
target3                 618
natlty3                 617
natlty3_txt             617
gname                 59395
gsubname               1842
gname2                 1144
gsubname2                74
gname3                  189
gsubname3                 6
motive                11456
guncertain1           59395
guncertain2            1144
guncertain3             189
individual            59395
nperps                59395
nperpcap              59394
claimed               59395
claimmode             11305
claimmode_txt         11305
claim2                 1144
claimmode2              316
claimmode2_txt          316
claim3                  189
claimmode3               50
claimmode3_txt           50
compclaim               315
weaptype1             59395
weaptype1_txt         59395
weapsubtype1          54417
weapsubtype1_txt      54417
weaptype2              5688
weaptype2_txt          5688
weapsubtype2           5057
weapsubtype2_txt       5057
weaptype3               975
weaptype3_txt           975
weapsubtype3            901
weapsubtype3_txt        901
weaptype4                 0
weaptype4_txt             0
weapsubtype4              0
weapsubtype4_txt          0
weapdetail            20854
nkill                 56395
nkillus               59386
nkillter              58632
nwound                54179
nwoundus              59366
nwoundte              57882
property              59395
propextent            25387
propextent_txt        25387
propvalue             25387
propcomment           32316
ishostkid             59395
nhostkid               6510
nhostkidus             6510
nhours                 1858
ndays                  4653
divert                   64
kidhijcountry            31
ransom                 6509
ransomamt               423
ransomamtus             416
ransompaid              422
ransompaidus            415
ransomnote              323
hostkidoutcome         6510
hostkidoutcome_txt     6510
nreleased              6511
addnotes              14540
scite1                59395
scite2                38212
scite3                23875
dbsource              59395
INT_LOG               59395
INT_IDEO              59395
INT_MISC              59395
INT_ANY               59395
related               11679
dtype: int64

In [39]:
df.shape

(59395, 135)

In [25]:
# write to csv
terrorism_by_year.to_csv('../data/derived/terrorism_by_year.csv')